///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FeedIssueListItemListDataWebUrl {
/*
{
  "raw": "http://www.eyepetizer.net/detail.html?vid=138044",
  "forWeibo": "http://www.eyepetizer.net/detail.html?vid=138044&resourceType=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
} 
*/

  String? raw;
  String? forWeibo;

  FeedIssueListItemListDataWebUrl({
    this.raw,
    this.forWeibo,
  });
  FeedIssueListItemListDataWebUrl.fromJson(Map<String, dynamic> json) {
    raw = json["raw"]?.toString();
    forWeibo = json["forWeibo"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["raw"] = raw;
    data["forWeibo"] = forWeibo;
    return data;
  }
}

class FeedIssueListItemListDataCover {
/*
{
  "feed": "http://img.kaiyanapp.com/7b4a185b11a1df25bb3e88ece4a49408.jpeg?imageMogr2/quality/60/format/jpg",
  "detail": "http://img.kaiyanapp.com/7b4a185b11a1df25bb3e88ece4a49408.jpeg?imageMogr2/quality/60/format/jpg",
  "blurred": "http://img.kaiyanapp.com/152ac8bc2b41afb6e599f9a02c034d68.jpeg?imageMogr2/quality/60/format/jpg",
  "homepage": "http://img.kaiyanapp.com/7b4a185b11a1df25bb3e88ece4a49408.jpeg?imageView2/1/w/720/h/560/format/jpg/q/75|watermark/1/image/aHR0cDovL2ltZy5rYWl5YW5hcHAuY29tL2JsYWNrXzMwLnBuZw==/dissolve/100/gravity/Center/dx/0/dy/0|imageslim"
} 
*/

  String? feed;
  String? detail;
  String? blurred;
  String? homepage;

  FeedIssueListItemListDataCover({
    this.feed,
    this.detail,
    this.blurred,
    this.homepage,
  });
  FeedIssueListItemListDataCover.fromJson(Map<String, dynamic> json) {
    feed = json["feed"]?.toString();
    detail = json["detail"]?.toString();
    blurred = json["blurred"]?.toString();
    homepage = json["homepage"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["feed"] = feed;
    data["detail"] = detail;
    data["blurred"] = blurred;
    data["homepage"] = homepage;
    return data;
  }
}

class FeedIssueListItemListDataAuthorShield {
/*
{
  "itemType": "author",
  "itemId": 3642,
  "shielded": false
} 
*/

  String? itemType;
  int? itemId;
  bool? shielded;

  FeedIssueListItemListDataAuthorShield({
    this.itemType,
    this.itemId,
    this.shielded,
  });
  FeedIssueListItemListDataAuthorShield.fromJson(Map<String, dynamic> json) {
    itemType = json["itemType"]?.toString();
    itemId = json["itemId"]?.toInt();
    shielded = json["shielded"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["itemType"] = itemType;
    data["itemId"] = itemId;
    data["shielded"] = shielded;
    return data;
  }
}

class FeedIssueListItemListDataAuthorFollow {
/*
{
  "itemType": "author",
  "itemId": 3642,
  "followed": false
} 
*/

  String? itemType;
  int? itemId;
  bool? followed;

  FeedIssueListItemListDataAuthorFollow({
    this.itemType,
    this.itemId,
    this.followed,
  });
  FeedIssueListItemListDataAuthorFollow.fromJson(Map<String, dynamic> json) {
    itemType = json["itemType"]?.toString();
    itemId = json["itemId"]?.toInt();
    followed = json["followed"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["itemType"] = itemType;
    data["itemId"] = itemId;
    data["followed"] = followed;
    return data;
  }
}

class FeedIssueListItemListDataAuthor {
/*
{
  "id": 3642,
  "icon": "http://img.kaiyanapp.com/41a3867b0ffc0814c9b23585d750da40.jpeg?imageMogr2/quality/60/format/jpg",
  "name": "竹蜻蜓",
  "description": "爱摄影，被摄影所爱，在用相机和无人机，记录这个地球的每一处美",
  "link": "",
  "latestReleaseTime": 1628211600000,
  "videoNum": 63,
  "follow": {
    "itemType": "author",
    "itemId": 3642,
    "followed": false
  },
  "shield": {
    "itemType": "author",
    "itemId": 3642,
    "shielded": false
  },
  "approvedNotReadyVideoCount": 0,
  "ifPgc": true,
  "recSort": 0,
  "expert": false
} 
*/

  int? id;
  String? icon;
  String? name;
  String? description;
  String? link;
  int? latestReleaseTime;
  int? videoNum;
  FeedIssueListItemListDataAuthorFollow? follow;
  FeedIssueListItemListDataAuthorShield? shield;
  int? approvedNotReadyVideoCount;
  bool? ifPgc;
  int? recSort;
  bool? expert;

  FeedIssueListItemListDataAuthor({
    this.id,
    this.icon,
    this.name,
    this.description,
    this.link,
    this.latestReleaseTime,
    this.videoNum,
    this.follow,
    this.shield,
    this.approvedNotReadyVideoCount,
    this.ifPgc,
    this.recSort,
    this.expert,
  });
  FeedIssueListItemListDataAuthor.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    icon = json["icon"]?.toString();
    name = json["name"]?.toString();
    description = json["description"]?.toString();
    link = json["link"]?.toString();
    latestReleaseTime = json["latestReleaseTime"]?.toInt();
    videoNum = json["videoNum"]?.toInt();
    follow = (json["follow"] != null)
        ? FeedIssueListItemListDataAuthorFollow.fromJson(json["follow"])
        : null;
    shield = (json["shield"] != null)
        ? FeedIssueListItemListDataAuthorShield.fromJson(json["shield"])
        : null;
    approvedNotReadyVideoCount = json["approvedNotReadyVideoCount"]?.toInt();
    ifPgc = json["ifPgc"];
    recSort = json["recSort"]?.toInt();
    expert = json["expert"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["icon"] = icon;
    data["name"] = name;
    data["description"] = description;
    data["link"] = link;
    data["latestReleaseTime"] = latestReleaseTime;
    data["videoNum"] = videoNum;
    if (follow != null) {
      data["follow"] = follow!.toJson();
    }
    if (shield != null) {
      data["shield"] = shield!.toJson();
    }
    data["approvedNotReadyVideoCount"] = approvedNotReadyVideoCount;
    data["ifPgc"] = ifPgc;
    data["recSort"] = recSort;
    data["expert"] = expert;
    return data;
  }
}

class FeedIssueListItemListDataProvider {
/*
{
  "name": "定制来源",
  "alias": "CustomSrc",
  "icon": ""
} 
*/

  String? name;
  String? alias;
  String? icon;

  FeedIssueListItemListDataProvider({
    this.name,
    this.alias,
    this.icon,
  });
  FeedIssueListItemListDataProvider.fromJson(Map<String, dynamic> json) {
    name = json["name"]?.toString();
    alias = json["alias"]?.toString();
    icon = json["icon"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["name"] = name;
    data["alias"] = alias;
    data["icon"] = icon;
    return data;
  }
}

class FeedIssueListItemListDataConsumption {
/*
{
  "collectionCount": 335,
  "shareCount": 238,
  "replyCount": 13,
  "realCollectionCount": 320
} 
*/

  int? collectionCount;
  int? shareCount;
  int? replyCount;
  int? realCollectionCount;

  FeedIssueListItemListDataConsumption({
    this.collectionCount,
    this.shareCount,
    this.replyCount,
    this.realCollectionCount,
  });
  FeedIssueListItemListDataConsumption.fromJson(Map<String, dynamic> json) {
    collectionCount = json["collectionCount"]?.toInt();
    shareCount = json["shareCount"]?.toInt();
    replyCount = json["replyCount"]?.toInt();
    realCollectionCount = json["realCollectionCount"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["collectionCount"] = collectionCount;
    data["shareCount"] = shareCount;
    data["replyCount"] = replyCount;
    data["realCollectionCount"] = realCollectionCount;
    return data;
  }
}

class FeedIssueListItemListData {
/*
{
  "dataType": "VideoBeanForClient",
  "id": 138044,
  "title": "2 分钟带你游日本，人生必去旅行地！",
  "description": "有时当你旅行时，你会被周围的一切能量所吸引。在这部影片中，我试图总结我在日本之旅中的所有感受，这是一个传统与现代的对比。我希望你喜欢它，让你想去参观这些神奇的岛屿。From Pau Garcia Laita",
  "library": "DAILY",
  "consumption": {
    "collectionCount": 335,
    "shareCount": 238,
    "replyCount": 13,
    "realCollectionCount": 320
  },
  "resourceType": "video",
  "provider": {
    "name": "定制来源",
    "alias": "CustomSrc",
    "icon": ""
  },
  "category": "旅行",
  "author": {
    "id": 3642,
    "icon": "http://img.kaiyanapp.com/41a3867b0ffc0814c9b23585d750da40.jpeg?imageMogr2/quality/60/format/jpg",
    "name": "竹蜻蜓",
    "description": "爱摄影，被摄影所爱，在用相机和无人机，记录这个地球的每一处美",
    "link": "",
    "latestReleaseTime": 1628211600000,
    "videoNum": 63,
    "follow": {
      "itemType": "author",
      "itemId": 3642,
      "followed": false
    },
    "shield": {
      "itemType": "author",
      "itemId": 3642,
      "shielded": false
    },
    "approvedNotReadyVideoCount": 0,
    "ifPgc": true,
    "recSort": 0,
    "expert": false
  },
  "cover": {
    "feed": "http://img.kaiyanapp.com/7b4a185b11a1df25bb3e88ece4a49408.jpeg?imageMogr2/quality/60/format/jpg",
    "detail": "http://img.kaiyanapp.com/7b4a185b11a1df25bb3e88ece4a49408.jpeg?imageMogr2/quality/60/format/jpg",
    "blurred": "http://img.kaiyanapp.com/152ac8bc2b41afb6e599f9a02c034d68.jpeg?imageMogr2/quality/60/format/jpg",
    "homepage": "http://img.kaiyanapp.com/7b4a185b11a1df25bb3e88ece4a49408.jpeg?imageView2/1/w/720/h/560/format/jpg/q/75|watermark/1/image/aHR0cDovL2ltZy5rYWl5YW5hcHAuY29tL2JsYWNrXzMwLnBuZw==/dissolve/100/gravity/Center/dx/0/dy/0|imageslim"
  },
  "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=138044&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
  "duration": 147,
  "webUrl": {
    "raw": "http://www.eyepetizer.net/detail.html?vid=138044",
    "forWeibo": "http://www.eyepetizer.net/detail.html?vid=138044&resourceType=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
  },
  "releaseTime": 1600185661000,
  "ad": false,
  "type": "NORMAL",
  "descriptionPgc": "",
  "remark": "",
  "ifLimitVideo": false,
  "searchWeight": 0,
  "idx": 0,
  "date": 1633914000000,
  "descriptionEditor": "有时当你旅行时，你会被周围的一切能量所吸引。在这部影片中，我试图总结我在日本之旅中的所有感受，这是一个传统与现代的对比。我希望你喜欢它，让你想去参观这些神奇的岛屿。From Pau Garcia Laita",
  "collected": false,
  "reallyCollected": false,
  "played": false
} 
*/

  String? dataType;
  int? id;
  String? title;
  String? description;
  String? theLibrary;
  FeedIssueListItemListDataConsumption? consumption;
  String? resourceType;
  FeedIssueListItemListDataProvider? provider;
  String? category;
  FeedIssueListItemListDataAuthor? author;
  FeedIssueListItemListDataCover? cover;
  String? playUrl;
  int? duration;
  FeedIssueListItemListDataWebUrl? webUrl;
  int? releaseTime;
  bool? ad;
  String? type;
  String? descriptionPgc;
  String? remark;
  bool? ifLimitVideo;
  int? searchWeight;
  int? idx;
  int? date;
  String? descriptionEditor;
  bool? collected;
  bool? reallyCollected;
  bool? played;

  FeedIssueListItemListData({
    this.dataType,
    this.id,
    this.title,
    this.description,
    this.theLibrary,
    this.consumption,
    this.resourceType,
    this.provider,
    this.category,
    this.author,
    this.cover,
    this.playUrl,
    this.duration,
    this.webUrl,
    this.releaseTime,
    this.ad,
    this.type,
    this.descriptionPgc,
    this.remark,
    this.ifLimitVideo,
    this.searchWeight,
    this.idx,
    this.date,
    this.descriptionEditor,
    this.collected,
    this.reallyCollected,
    this.played,
  });
  FeedIssueListItemListData.fromJson(Map<String, dynamic> json) {
    dataType = json["dataType"]?.toString();
    id = json["id"]?.toInt();
    title = json["title"]?.toString();
    description = json["description"]?.toString();
    theLibrary = json["library"]?.toString();
    consumption = (json["consumption"] != null)
        ? FeedIssueListItemListDataConsumption.fromJson(json["consumption"])
        : null;
    resourceType = json["resourceType"]?.toString();
    provider = (json["provider"] != null)
        ? FeedIssueListItemListDataProvider.fromJson(json["provider"])
        : null;
    category = json["category"]?.toString();
    author = (json["author"] != null)
        ? FeedIssueListItemListDataAuthor.fromJson(json["author"])
        : null;
    cover = (json["cover"] != null)
        ? FeedIssueListItemListDataCover.fromJson(json["cover"])
        : null;
    playUrl = json["playUrl"]?.toString();
    duration = json["duration"]?.toInt();
    webUrl = (json["webUrl"] != null)
        ? FeedIssueListItemListDataWebUrl.fromJson(json["webUrl"])
        : null;
    releaseTime = json["releaseTime"]?.toInt();
    ad = json["ad"];
    type = json["type"]?.toString();
    descriptionPgc = json["descriptionPgc"]?.toString();
    remark = json["remark"]?.toString();
    ifLimitVideo = json["ifLimitVideo"];
    searchWeight = json["searchWeight"]?.toInt();
    idx = json["idx"]?.toInt();
    date = json["date"]?.toInt();
    descriptionEditor = json["descriptionEditor"]?.toString();
    collected = json["collected"];
    reallyCollected = json["reallyCollected"];
    played = json["played"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["dataType"] = dataType;
    data["id"] = id;
    data["title"] = title;
    data["description"] = description;
    data["library"] = theLibrary;
    if (consumption != null) {
      data["consumption"] = consumption!.toJson();
    }
    data["resourceType"] = resourceType;
    if (provider != null) {
      data["provider"] = provider!.toJson();
    }
    data["category"] = category;
    if (author != null) {
      data["author"] = author!.toJson();
    }
    if (cover != null) {
      data["cover"] = cover!.toJson();
    }
    data["playUrl"] = playUrl;
    data["duration"] = duration;
    if (webUrl != null) {
      data["webUrl"] = webUrl!.toJson();
    }
    data["releaseTime"] = releaseTime;
    data["ad"] = ad;
    data["type"] = type;
    data["descriptionPgc"] = descriptionPgc;
    data["remark"] = remark;
    data["ifLimitVideo"] = ifLimitVideo;
    data["searchWeight"] = searchWeight;
    data["idx"] = idx;
    data["date"] = date;
    data["descriptionEditor"] = descriptionEditor;
    data["collected"] = collected;
    data["reallyCollected"] = reallyCollected;
    data["played"] = played;
    return data;
  }
}

class FeedIssueListItemList {
/*
{
  "type": "video",
  "data": {
    "dataType": "VideoBeanForClient",
    "id": 138044,
    "title": "2 分钟带你游日本，人生必去旅行地！",
    "description": "有时当你旅行时，你会被周围的一切能量所吸引。在这部影片中，我试图总结我在日本之旅中的所有感受，这是一个传统与现代的对比。我希望你喜欢它，让你想去参观这些神奇的岛屿。From Pau Garcia Laita",
    "library": "DAILY",
    "consumption": {
      "collectionCount": 335,
      "shareCount": 238,
      "replyCount": 13,
      "realCollectionCount": 320
    },
    "resourceType": "video",
    "provider": {
      "name": "定制来源",
      "alias": "CustomSrc",
      "icon": ""
    },
    "category": "旅行",
    "author": {
      "id": 3642,
      "icon": "http://img.kaiyanapp.com/41a3867b0ffc0814c9b23585d750da40.jpeg?imageMogr2/quality/60/format/jpg",
      "name": "竹蜻蜓",
      "description": "爱摄影，被摄影所爱，在用相机和无人机，记录这个地球的每一处美",
      "link": "",
      "latestReleaseTime": 1628211600000,
      "videoNum": 63,
      "follow": {
        "itemType": "author",
        "itemId": 3642,
        "followed": false
      },
      "shield": {
        "itemType": "author",
        "itemId": 3642,
        "shielded": false
      },
      "approvedNotReadyVideoCount": 0,
      "ifPgc": true,
      "recSort": 0,
      "expert": false
    },
    "cover": {
      "feed": "http://img.kaiyanapp.com/7b4a185b11a1df25bb3e88ece4a49408.jpeg?imageMogr2/quality/60/format/jpg",
      "detail": "http://img.kaiyanapp.com/7b4a185b11a1df25bb3e88ece4a49408.jpeg?imageMogr2/quality/60/format/jpg",
      "blurred": "http://img.kaiyanapp.com/152ac8bc2b41afb6e599f9a02c034d68.jpeg?imageMogr2/quality/60/format/jpg",
      "homepage": "http://img.kaiyanapp.com/7b4a185b11a1df25bb3e88ece4a49408.jpeg?imageView2/1/w/720/h/560/format/jpg/q/75|watermark/1/image/aHR0cDovL2ltZy5rYWl5YW5hcHAuY29tL2JsYWNrXzMwLnBuZw==/dissolve/100/gravity/Center/dx/0/dy/0|imageslim"
    },
    "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=138044&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
    "duration": 147,
    "webUrl": {
      "raw": "http://www.eyepetizer.net/detail.html?vid=138044",
      "forWeibo": "http://www.eyepetizer.net/detail.html?vid=138044&resourceType=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
    },
    "releaseTime": 1600185661000,
    "ad": false,
    "type": "NORMAL",
    "descriptionPgc": "",
    "remark": "",
    "ifLimitVideo": false,
    "searchWeight": 0,
    "idx": 0,
    "date": 1633914000000,
    "descriptionEditor": "有时当你旅行时，你会被周围的一切能量所吸引。在这部影片中，我试图总结我在日本之旅中的所有感受，这是一个传统与现代的对比。我希望你喜欢它，让你想去参观这些神奇的岛屿。From Pau Garcia Laita",
    "collected": false,
    "reallyCollected": false,
    "played": false
  },
  "id": 0,
  "adIndex": -1
} 
*/

  String? type;
  FeedIssueListItemListData? data;
  int? id;
  int? adIndex;

  FeedIssueListItemList({
    this.type,
    this.data,
    this.id,
    this.adIndex,
  });
  FeedIssueListItemList.fromJson(Map<String, dynamic> json) {
    type = json["type"]?.toString();
    data = (json["data"] != null)
        ? FeedIssueListItemListData.fromJson(json["data"])
        : null;
    id = json["id"]?.toInt();
    adIndex = json["adIndex"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["type"] = type;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["id"] = id;
    data["adIndex"] = adIndex;
    return data;
  }
}

class FeedIssueList {
/*
{
  "releaseTime": 1633914000000,
  "type": "morning",
  "date": 1633914000000,
  "publishTime": 1633914000000,
  "itemList": [
    {
      "type": "video",
      "data": {
        "dataType": "VideoBeanForClient",
        "id": 138044,
        "title": "2 分钟带你游日本，人生必去旅行地！",
        "description": "有时当你旅行时，你会被周围的一切能量所吸引。在这部影片中，我试图总结我在日本之旅中的所有感受，这是一个传统与现代的对比。我希望你喜欢它，让你想去参观这些神奇的岛屿。From Pau Garcia Laita",
        "library": "DAILY",
        "consumption": {
          "collectionCount": 335,
          "shareCount": 238,
          "replyCount": 13,
          "realCollectionCount": 320
        },
        "resourceType": "video",
        "provider": {
          "name": "定制来源",
          "alias": "CustomSrc",
          "icon": ""
        },
        "category": "旅行",
        "author": {
          "id": 3642,
          "icon": "http://img.kaiyanapp.com/41a3867b0ffc0814c9b23585d750da40.jpeg?imageMogr2/quality/60/format/jpg",
          "name": "竹蜻蜓",
          "description": "爱摄影，被摄影所爱，在用相机和无人机，记录这个地球的每一处美",
          "link": "",
          "latestReleaseTime": 1628211600000,
          "videoNum": 63,
          "follow": {
            "itemType": "author",
            "itemId": 3642,
            "followed": false
          },
          "shield": {
            "itemType": "author",
            "itemId": 3642,
            "shielded": false
          },
          "approvedNotReadyVideoCount": 0,
          "ifPgc": true,
          "recSort": 0,
          "expert": false
        },
        "cover": {
          "feed": "http://img.kaiyanapp.com/7b4a185b11a1df25bb3e88ece4a49408.jpeg?imageMogr2/quality/60/format/jpg",
          "detail": "http://img.kaiyanapp.com/7b4a185b11a1df25bb3e88ece4a49408.jpeg?imageMogr2/quality/60/format/jpg",
          "blurred": "http://img.kaiyanapp.com/152ac8bc2b41afb6e599f9a02c034d68.jpeg?imageMogr2/quality/60/format/jpg",
          "homepage": "http://img.kaiyanapp.com/7b4a185b11a1df25bb3e88ece4a49408.jpeg?imageView2/1/w/720/h/560/format/jpg/q/75|watermark/1/image/aHR0cDovL2ltZy5rYWl5YW5hcHAuY29tL2JsYWNrXzMwLnBuZw==/dissolve/100/gravity/Center/dx/0/dy/0|imageslim"
        },
        "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=138044&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
        "duration": 147,
        "webUrl": {
          "raw": "http://www.eyepetizer.net/detail.html?vid=138044",
          "forWeibo": "http://www.eyepetizer.net/detail.html?vid=138044&resourceType=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
        },
        "releaseTime": 1600185661000,
        "ad": false,
        "type": "NORMAL",
        "descriptionPgc": "",
        "remark": "",
        "ifLimitVideo": false,
        "searchWeight": 0,
        "idx": 0,
        "date": 1633914000000,
        "descriptionEditor": "有时当你旅行时，你会被周围的一切能量所吸引。在这部影片中，我试图总结我在日本之旅中的所有感受，这是一个传统与现代的对比。我希望你喜欢它，让你想去参观这些神奇的岛屿。From Pau Garcia Laita",
        "collected": false,
        "reallyCollected": false,
        "played": false
      },
      "id": 0,
      "adIndex": -1
    }
  ],
  "count": 10
} 
*/

  int? releaseTime;
  String? type;
  int? date;
  int? publishTime;
  List<FeedIssueListItemList>? itemList;
  int? count;

  FeedIssueList({
    this.releaseTime,
    this.type,
    this.date,
    this.publishTime,
    this.itemList,
    this.count,
  });
  FeedIssueList.fromJson(Map<String, dynamic> json) {
    releaseTime = json["releaseTime"]?.toInt();
    type = json["type"]?.toString();
    date = json["date"]?.toInt();
    publishTime = json["publishTime"]?.toInt();
    if (json["itemList"] != null) {
      final v = json["itemList"];
      final arr0 = <FeedIssueListItemList>[];
      v.forEach((v) {
        // 类型判断，如果不是video就不需要
        if (v["type"] == "video") {
          arr0.add(FeedIssueListItemList.fromJson(v));
        }
      });
      itemList = arr0;
    }
    count = json["count"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["releaseTime"] = releaseTime;
    data["type"] = type;
    data["date"] = date;
    data["publishTime"] = publishTime;
    if (itemList != null) {
      final v = itemList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v.toJson());
      });
      data["itemList"] = arr0;
    }
    data["count"] = count;
    return data;
  }
}

class Feed {
/*
{
  "issueList": [
    {
      "releaseTime": 1633914000000,
      "type": "morning",
      "date": 1633914000000,
      "publishTime": 1633914000000,
      "itemList": [
        {
          "type": "video",
          "data": {
            "dataType": "VideoBeanForClient",
            "id": 138044,
            "title": "2 分钟带你游日本，人生必去旅行地！",
            "description": "有时当你旅行时，你会被周围的一切能量所吸引。在这部影片中，我试图总结我在日本之旅中的所有感受，这是一个传统与现代的对比。我希望你喜欢它，让你想去参观这些神奇的岛屿。From Pau Garcia Laita",
            "library": "DAILY",
            "consumption": {
              "collectionCount": 335,
              "shareCount": 238,
              "replyCount": 13,
              "realCollectionCount": 320
            },
            "resourceType": "video",
            "provider": {
              "name": "定制来源",
              "alias": "CustomSrc",
              "icon": ""
            },
            "category": "旅行",
            "author": {
              "id": 3642,
              "icon": "http://img.kaiyanapp.com/41a3867b0ffc0814c9b23585d750da40.jpeg?imageMogr2/quality/60/format/jpg",
              "name": "竹蜻蜓",
              "description": "爱摄影，被摄影所爱，在用相机和无人机，记录这个地球的每一处美",
              "link": "",
              "latestReleaseTime": 1628211600000,
              "videoNum": 63,
              "follow": {
                "itemType": "author",
                "itemId": 3642,
                "followed": false
              },
              "shield": {
                "itemType": "author",
                "itemId": 3642,
                "shielded": false
              },
              "approvedNotReadyVideoCount": 0,
              "ifPgc": true,
              "recSort": 0,
              "expert": false
            },
            "cover": {
              "feed": "http://img.kaiyanapp.com/7b4a185b11a1df25bb3e88ece4a49408.jpeg?imageMogr2/quality/60/format/jpg",
              "detail": "http://img.kaiyanapp.com/7b4a185b11a1df25bb3e88ece4a49408.jpeg?imageMogr2/quality/60/format/jpg",
              "blurred": "http://img.kaiyanapp.com/152ac8bc2b41afb6e599f9a02c034d68.jpeg?imageMogr2/quality/60/format/jpg",
              "homepage": "http://img.kaiyanapp.com/7b4a185b11a1df25bb3e88ece4a49408.jpeg?imageView2/1/w/720/h/560/format/jpg/q/75|watermark/1/image/aHR0cDovL2ltZy5rYWl5YW5hcHAuY29tL2JsYWNrXzMwLnBuZw==/dissolve/100/gravity/Center/dx/0/dy/0|imageslim"
            },
            "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=138044&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
            "duration": 147,
            "webUrl": {
              "raw": "http://www.eyepetizer.net/detail.html?vid=138044",
              "forWeibo": "http://www.eyepetizer.net/detail.html?vid=138044&resourceType=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
            },
            "releaseTime": 1600185661000,
            "ad": false,
            "type": "NORMAL",
            "descriptionPgc": "",
            "remark": "",
            "ifLimitVideo": false,
            "searchWeight": 0,
            "idx": 0,
            "date": 1633914000000,
            "descriptionEditor": "有时当你旅行时，你会被周围的一切能量所吸引。在这部影片中，我试图总结我在日本之旅中的所有感受，这是一个传统与现代的对比。我希望你喜欢它，让你想去参观这些神奇的岛屿。From Pau Garcia Laita",
            "collected": false,
            "reallyCollected": false,
            "played": false
          },
          "id": 0,
          "adIndex": -1
        }
      ],
      "count": 10
    }
  ],
  "nextPageUrl": "https://baobab.kaiyanapp.com/api/v2/feed?date=1633827600000&num=1",
  "nextPublishTime": 1634000400000,
  "newestIssueType": "morning"
} 
*/

  List<FeedIssueList?>? issueList;
  String? nextPageUrl;
  int? nextPublishTime;
  String? newestIssueType;

  Feed({
    this.issueList,
    this.nextPageUrl,
    this.nextPublishTime,
    this.newestIssueType,
  });
  Feed.fromJson(Map<String, dynamic> json) {
    if (json["issueList"] != null) {
      final v = json["issueList"];
      final arr0 = <FeedIssueList>[];
      v.forEach((v) {
        arr0.add(FeedIssueList.fromJson(v));
      });
      issueList = arr0;
    }
    nextPageUrl = json["nextPageUrl"]?.toString();
    nextPublishTime = json["nextPublishTime"]?.toInt();
    newestIssueType = json["newestIssueType"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (issueList != null) {
      final v = issueList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["issueList"] = arr0;
    }
    data["nextPageUrl"] = nextPageUrl;
    data["nextPublishTime"] = nextPublishTime;
    data["newestIssueType"] = newestIssueType;
    return data;
  }
}
