///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FollowItemListDataItemListDataWebUrl {
/*
{
  "raw": "http://www.eyepetizer.net/detail.html?vid=194586",
  "forWeibo": "http://www.eyepetizer.net/detail.html?vid=194586&resourceType=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
} 
*/

  String? raw;
  String? forWeibo;

  FollowItemListDataItemListDataWebUrl({
    this.raw,
    this.forWeibo,
  });
  FollowItemListDataItemListDataWebUrl.fromJson(Map<String, dynamic> json) {
    raw = json["raw"]?.toString();
    forWeibo = json["forWeibo"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["raw"] = raw;
    data["forWeibo"] = forWeibo;
    return data;
  }
}

class FollowItemListDataItemListDataCover {
/*
{
  "feed": "http://img.kaiyanapp.com/ef8aab4eb02d7169d98acfd1e4e8d1e4.png?imageMogr2/quality/60/format/jpg",
  "detail": "http://img.kaiyanapp.com/ef8aab4eb02d7169d98acfd1e4e8d1e4.png?imageMogr2/quality/60/format/jpg",
  "blurred": "http://img.kaiyanapp.com/a7b8e9927e9e0bcbf9b8755f798a4c25.jpeg?imageMogr2/quality/60/format/jpg"
} 
*/

  String? feed;
  String? detail;
  String? blurred;

  FollowItemListDataItemListDataCover({
    this.feed,
    this.detail,
    this.blurred,
  });
  FollowItemListDataItemListDataCover.fromJson(Map<String, dynamic> json) {
    feed = json["feed"]?.toString();
    detail = json["detail"]?.toString();
    blurred = json["blurred"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["feed"] = feed;
    data["detail"] = detail;
    data["blurred"] = blurred;
    return data;
  }
}

class FollowItemListDataItemListDataAuthorShield {
/*
{
  "itemType": "author",
  "itemId": 3443,
  "shielded": false
} 
*/

  String? itemType;
  int? itemId;
  bool? shielded;

  FollowItemListDataItemListDataAuthorShield({
    this.itemType,
    this.itemId,
    this.shielded,
  });
  FollowItemListDataItemListDataAuthorShield.fromJson(
      Map<String, dynamic> json) {
    itemType = json["itemType"]?.toString();
    itemId = json["itemId"]?.toInt();
    shielded = json["shielded"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["itemType"] = itemType;
    data["itemId"] = itemId;
    data["shielded"] = shielded;
    return data;
  }
}

class FollowItemListDataItemListDataAuthorFollow {
/*
{
  "itemType": "author",
  "itemId": 3443,
  "followed": false
} 
*/

  String? itemType;
  int? itemId;
  bool? followed;

  FollowItemListDataItemListDataAuthorFollow({
    this.itemType,
    this.itemId,
    this.followed,
  });
  FollowItemListDataItemListDataAuthorFollow.fromJson(
      Map<String, dynamic> json) {
    itemType = json["itemType"]?.toString();
    itemId = json["itemId"]?.toInt();
    followed = json["followed"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["itemType"] = itemType;
    data["itemId"] = itemId;
    data["followed"] = followed;
    return data;
  }
}

class FollowItemListDataItemListDataAuthor {
/*
{
  "id": 3443,
  "icon": "http://img.kaiyanapp.com/97f314dfee63a00107e177a174858303.png?imageMogr2/quality/60/format/jpg",
  "name": "姚舜不二",
  "description": "93年 62国\n独立跳伞员/滑翔伞员 水肺教练\n冲浪手 旅行体验师\n",
  "link": "",
  "latestReleaseTime": 1589517738000,
  "videoNum": 14,
  "follow": {
    "itemType": "author",
    "itemId": 3443,
    "followed": false
  },
  "shield": {
    "itemType": "author",
    "itemId": 3443,
    "shielded": false
  },
  "approvedNotReadyVideoCount": 0,
  "ifPgc": true,
  "recSort": 0,
  "expert": false
} 
*/

  int? id;
  String? icon;
  String? name;
  String? description;
  String? link;
  int? latestReleaseTime;
  int? videoNum;
  FollowItemListDataItemListDataAuthorFollow? follow;
  FollowItemListDataItemListDataAuthorShield? shield;
  int? approvedNotReadyVideoCount;
  bool? ifPgc;
  int? recSort;
  bool? expert;

  FollowItemListDataItemListDataAuthor({
    this.id,
    this.icon,
    this.name,
    this.description,
    this.link,
    this.latestReleaseTime,
    this.videoNum,
    this.follow,
    this.shield,
    this.approvedNotReadyVideoCount,
    this.ifPgc,
    this.recSort,
    this.expert,
  });
  FollowItemListDataItemListDataAuthor.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    icon = json["icon"]?.toString();
    name = json["name"]?.toString();
    description = json["description"]?.toString();
    link = json["link"]?.toString();
    latestReleaseTime = json["latestReleaseTime"]?.toInt();
    videoNum = json["videoNum"]?.toInt();
    follow = (json["follow"] != null)
        ? FollowItemListDataItemListDataAuthorFollow.fromJson(json["follow"])
        : null;
    shield = (json["shield"] != null)
        ? FollowItemListDataItemListDataAuthorShield.fromJson(json["shield"])
        : null;
    approvedNotReadyVideoCount = json["approvedNotReadyVideoCount"]?.toInt();
    ifPgc = json["ifPgc"];
    recSort = json["recSort"]?.toInt();
    expert = json["expert"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["icon"] = icon;
    data["name"] = name;
    data["description"] = description;
    data["link"] = link;
    data["latestReleaseTime"] = latestReleaseTime;
    data["videoNum"] = videoNum;
    if (follow != null) {
      data["follow"] = follow!.toJson();
    }
    if (shield != null) {
      data["shield"] = shield!.toJson();
    }
    data["approvedNotReadyVideoCount"] = approvedNotReadyVideoCount;
    data["ifPgc"] = ifPgc;
    data["recSort"] = recSort;
    data["expert"] = expert;
    return data;
  }
}

class FollowItemListDataItemListDataConsumption {
/*
{
  "collectionCount": 30,
  "shareCount": 21,
  "replyCount": 1,
  "realCollectionCount": 0
} 
*/

  int? collectionCount;
  int? shareCount;
  int? replyCount;
  int? realCollectionCount;

  FollowItemListDataItemListDataConsumption({
    this.collectionCount,
    this.shareCount,
    this.replyCount,
    this.realCollectionCount,
  });
  FollowItemListDataItemListDataConsumption.fromJson(
      Map<String, dynamic> json) {
    collectionCount = json["collectionCount"]?.toInt();
    shareCount = json["shareCount"]?.toInt();
    replyCount = json["replyCount"]?.toInt();
    realCollectionCount = json["realCollectionCount"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["collectionCount"] = collectionCount;
    data["shareCount"] = shareCount;
    data["replyCount"] = replyCount;
    data["realCollectionCount"] = realCollectionCount;
    return data;
  }
}

class FollowItemListDataItemListDataTags {
/*
{
  "id": 10,
  "name": "跟着开眼看世界",
  "actionUrl": "eyepetizer://tag/10/?title=%E8%B7%9F%E7%9D%80%E5%BC%80%E7%9C%BC%E7%9C%8B%E4%B8%96%E7%95%8C",
  "desc": "去你想去的地方，发现世界的美",
  "bgPicture": "http://img.kaiyanapp.com/7ea328a893aa1f092b9328a53494a267.png?imageMogr2/quality/60/format/jpg",
  "headerImage": "http://img.kaiyanapp.com/50dab5468ecd2dbe5eb99dab5d608a0a.jpeg?imageMogr2/quality/60/format/jpg",
  "tagRecType": "IMPORTANT",
  "haveReward": false,
  "ifNewest": false,
  "communityIndex": 14
} 
*/

  int? id;
  String? name;
  String? actionUrl;
  String? desc;
  String? bgPicture;
  String? headerImage;
  String? tagRecType;
  bool? haveReward;
  bool? ifNewest;
  int? communityIndex;

  FollowItemListDataItemListDataTags({
    this.id,
    this.name,
    this.actionUrl,
    this.desc,
    this.bgPicture,
    this.headerImage,
    this.tagRecType,
    this.haveReward,
    this.ifNewest,
    this.communityIndex,
  });
  FollowItemListDataItemListDataTags.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    name = json["name"]?.toString();
    actionUrl = json["actionUrl"]?.toString();
    desc = json["desc"]?.toString();
    bgPicture = json["bgPicture"]?.toString();
    headerImage = json["headerImage"]?.toString();
    tagRecType = json["tagRecType"]?.toString();
    haveReward = json["haveReward"];
    ifNewest = json["ifNewest"];
    communityIndex = json["communityIndex"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["actionUrl"] = actionUrl;
    data["desc"] = desc;
    data["bgPicture"] = bgPicture;
    data["headerImage"] = headerImage;
    data["tagRecType"] = tagRecType;
    data["haveReward"] = haveReward;
    data["ifNewest"] = ifNewest;
    data["communityIndex"] = communityIndex;
    return data;
  }
}

class FollowItemListDataItemListData {
/*
{
  "dataType": "VideoBeanForClient",
  "id": 194586,
  "title": "Jeep自驾｜雪原万里 都是惊喜",
  "description": "雪原万里，都是大自然给予的惊喜。\n太阳从南半球回归，\n温暖也在不远之日。\n长路浩浩荡荡，\n万事皆可期待。\n你也一定要站在自己所热爱的世界里，\n闪闪发亮。",
  "library": "DEFAULT",
  "tags": [
    {
      "id": 10,
      "name": "跟着开眼看世界",
      "actionUrl": "eyepetizer://tag/10/?title=%E8%B7%9F%E7%9D%80%E5%BC%80%E7%9C%BC%E7%9C%8B%E4%B8%96%E7%95%8C",
      "desc": "去你想去的地方，发现世界的美",
      "bgPicture": "http://img.kaiyanapp.com/7ea328a893aa1f092b9328a53494a267.png?imageMogr2/quality/60/format/jpg",
      "headerImage": "http://img.kaiyanapp.com/50dab5468ecd2dbe5eb99dab5d608a0a.jpeg?imageMogr2/quality/60/format/jpg",
      "tagRecType": "IMPORTANT",
      "haveReward": false,
      "ifNewest": false,
      "communityIndex": 14
    }
  ],
  "consumption": {
    "collectionCount": 30,
    "shareCount": 21,
    "replyCount": 1,
    "realCollectionCount": 0
  },
  "resourceType": "video",
  "category": "旅行",
  "author": {
    "id": 3443,
    "icon": "http://img.kaiyanapp.com/97f314dfee63a00107e177a174858303.png?imageMogr2/quality/60/format/jpg",
    "name": "姚舜不二",
    "description": "93年 62国\n独立跳伞员/滑翔伞员 水肺教练\n冲浪手 旅行体验师\n",
    "link": "",
    "latestReleaseTime": 1589517738000,
    "videoNum": 14,
    "follow": {
      "itemType": "author",
      "itemId": 3443,
      "followed": false
    },
    "shield": {
      "itemType": "author",
      "itemId": 3443,
      "shielded": false
    },
    "approvedNotReadyVideoCount": 0,
    "ifPgc": true,
    "recSort": 0,
    "expert": false
  },
  "cover": {
    "feed": "http://img.kaiyanapp.com/ef8aab4eb02d7169d98acfd1e4e8d1e4.png?imageMogr2/quality/60/format/jpg",
    "detail": "http://img.kaiyanapp.com/ef8aab4eb02d7169d98acfd1e4e8d1e4.png?imageMogr2/quality/60/format/jpg",
    "blurred": "http://img.kaiyanapp.com/a7b8e9927e9e0bcbf9b8755f798a4c25.jpeg?imageMogr2/quality/60/format/jpg"
  },
  "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=194586&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
  "duration": 121,
  "webUrl": {
    "raw": "http://www.eyepetizer.net/detail.html?vid=194586",
    "forWeibo": "http://www.eyepetizer.net/detail.html?vid=194586&resourceType=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
  },
  "releaseTime": 1589517738000,
  "ad": false,
  "type": "NORMAL",
  "titlePgc": "Jeep自驾｜雪原万里 都是惊喜",
  "descriptionPgc": "雪原万里，都是大自然给予的惊喜。\n太阳从南半球回归，\n温暖也在不远之日。\n长路浩浩荡荡，\n万事皆可期待。\n你也一定要站在自己所热爱的世界里，\n闪闪发亮。",
  "remark": "",
  "ifLimitVideo": false,
  "searchWeight": 0,
  "idx": 0,
  "date": 1589517738000,
  "descriptionEditor": "",
  "collected": false,
  "reallyCollected": false,
  "played": false
} 
*/

  String? dataType;
  int? id;
  String? title;
  String? description;
  String? theLibrary;
  List<FollowItemListDataItemListDataTags?>? tags;
  FollowItemListDataItemListDataConsumption? consumption;
  String? resourceType;
  String? category;
  FollowItemListDataItemListDataAuthor? author;
  FollowItemListDataItemListDataCover? cover;
  String? playUrl;
  int? duration;
  FollowItemListDataItemListDataWebUrl? webUrl;
  int? releaseTime;
  bool? ad;
  String? type;
  String? titlePgc;
  String? descriptionPgc;
  String? remark;
  bool? ifLimitVideo;
  int? searchWeight;
  int? idx;
  int? date;
  String? descriptionEditor;
  bool? collected;
  bool? reallyCollected;
  bool? played;

  FollowItemListDataItemListData({
    this.dataType,
    this.id,
    this.title,
    this.description,
    this.theLibrary,
    this.tags,
    this.consumption,
    this.resourceType,
    this.category,
    this.author,
    this.cover,
    this.playUrl,
    this.duration,
    this.webUrl,
    this.releaseTime,
    this.ad,
    this.type,
    this.titlePgc,
    this.descriptionPgc,
    this.remark,
    this.ifLimitVideo,
    this.searchWeight,
    this.idx,
    this.date,
    this.descriptionEditor,
    this.collected,
    this.reallyCollected,
    this.played,
  });
  FollowItemListDataItemListData.fromJson(Map<String, dynamic> json) {
    dataType = json["dataType"]?.toString();
    id = json["id"]?.toInt();
    title = json["title"]?.toString();
    description = json["description"]?.toString();
    theLibrary = json["library"]?.toString();
    if (json["tags"] != null) {
      final v = json["tags"];
      final arr0 = <FollowItemListDataItemListDataTags>[];
      v.forEach((v) {
        arr0.add(FollowItemListDataItemListDataTags.fromJson(v));
      });
      tags = arr0;
    }
    consumption = (json["consumption"] != null)
        ? FollowItemListDataItemListDataConsumption.fromJson(
            json["consumption"])
        : null;
    resourceType = json["resourceType"]?.toString();
    category = json["category"]?.toString();
    author = (json["author"] != null)
        ? FollowItemListDataItemListDataAuthor.fromJson(json["author"])
        : null;
    cover = (json["cover"] != null)
        ? FollowItemListDataItemListDataCover.fromJson(json["cover"])
        : null;
    playUrl = json["playUrl"]?.toString();
    duration = json["duration"]?.toInt();
    webUrl = (json["webUrl"] != null)
        ? FollowItemListDataItemListDataWebUrl.fromJson(json["webUrl"])
        : null;
    releaseTime = json["releaseTime"]?.toInt();
    ad = json["ad"];
    type = json["type"]?.toString();
    titlePgc = json["titlePgc"]?.toString();
    descriptionPgc = json["descriptionPgc"]?.toString();
    remark = json["remark"]?.toString();
    ifLimitVideo = json["ifLimitVideo"];
    searchWeight = json["searchWeight"]?.toInt();
    idx = json["idx"]?.toInt();
    date = json["date"]?.toInt();
    descriptionEditor = json["descriptionEditor"]?.toString();
    collected = json["collected"];
    reallyCollected = json["reallyCollected"];
    played = json["played"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["dataType"] = dataType;
    data["id"] = id;
    data["title"] = title;
    data["description"] = description;
    data["library"] = theLibrary;
    if (tags != null) {
      final v = tags;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["tags"] = arr0;
    }
    if (consumption != null) {
      data["consumption"] = consumption!.toJson();
    }
    data["resourceType"] = resourceType;
    data["category"] = category;
    if (author != null) {
      data["author"] = author!.toJson();
    }
    if (cover != null) {
      data["cover"] = cover!.toJson();
    }
    data["playUrl"] = playUrl;
    data["duration"] = duration;
    if (webUrl != null) {
      data["webUrl"] = webUrl!.toJson();
    }
    data["releaseTime"] = releaseTime;
    data["ad"] = ad;
    data["type"] = type;
    data["titlePgc"] = titlePgc;
    data["descriptionPgc"] = descriptionPgc;
    data["remark"] = remark;
    data["ifLimitVideo"] = ifLimitVideo;
    data["searchWeight"] = searchWeight;
    data["idx"] = idx;
    data["date"] = date;
    data["descriptionEditor"] = descriptionEditor;
    data["collected"] = collected;
    data["reallyCollected"] = reallyCollected;
    data["played"] = played;
    return data;
  }
}

class FollowItemListDataItemList {
/*
{
  "type": "video",
  "data": {
    "dataType": "VideoBeanForClient",
    "id": 194586,
    "title": "Jeep自驾｜雪原万里 都是惊喜",
    "description": "雪原万里，都是大自然给予的惊喜。\n太阳从南半球回归，\n温暖也在不远之日。\n长路浩浩荡荡，\n万事皆可期待。\n你也一定要站在自己所热爱的世界里，\n闪闪发亮。",
    "library": "DEFAULT",
    "tags": [
      {
        "id": 10,
        "name": "跟着开眼看世界",
        "actionUrl": "eyepetizer://tag/10/?title=%E8%B7%9F%E7%9D%80%E5%BC%80%E7%9C%BC%E7%9C%8B%E4%B8%96%E7%95%8C",
        "desc": "去你想去的地方，发现世界的美",
        "bgPicture": "http://img.kaiyanapp.com/7ea328a893aa1f092b9328a53494a267.png?imageMogr2/quality/60/format/jpg",
        "headerImage": "http://img.kaiyanapp.com/50dab5468ecd2dbe5eb99dab5d608a0a.jpeg?imageMogr2/quality/60/format/jpg",
        "tagRecType": "IMPORTANT",
        "haveReward": false,
        "ifNewest": false,
        "communityIndex": 14
      }
    ],
    "consumption": {
      "collectionCount": 30,
      "shareCount": 21,
      "replyCount": 1,
      "realCollectionCount": 0
    },
    "resourceType": "video",
    "category": "旅行",
    "author": {
      "id": 3443,
      "icon": "http://img.kaiyanapp.com/97f314dfee63a00107e177a174858303.png?imageMogr2/quality/60/format/jpg",
      "name": "姚舜不二",
      "description": "93年 62国\n独立跳伞员/滑翔伞员 水肺教练\n冲浪手 旅行体验师\n",
      "link": "",
      "latestReleaseTime": 1589517738000,
      "videoNum": 14,
      "follow": {
        "itemType": "author",
        "itemId": 3443,
        "followed": false
      },
      "shield": {
        "itemType": "author",
        "itemId": 3443,
        "shielded": false
      },
      "approvedNotReadyVideoCount": 0,
      "ifPgc": true,
      "recSort": 0,
      "expert": false
    },
    "cover": {
      "feed": "http://img.kaiyanapp.com/ef8aab4eb02d7169d98acfd1e4e8d1e4.png?imageMogr2/quality/60/format/jpg",
      "detail": "http://img.kaiyanapp.com/ef8aab4eb02d7169d98acfd1e4e8d1e4.png?imageMogr2/quality/60/format/jpg",
      "blurred": "http://img.kaiyanapp.com/a7b8e9927e9e0bcbf9b8755f798a4c25.jpeg?imageMogr2/quality/60/format/jpg"
    },
    "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=194586&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
    "duration": 121,
    "webUrl": {
      "raw": "http://www.eyepetizer.net/detail.html?vid=194586",
      "forWeibo": "http://www.eyepetizer.net/detail.html?vid=194586&resourceType=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
    },
    "releaseTime": 1589517738000,
    "ad": false,
    "type": "NORMAL",
    "titlePgc": "Jeep自驾｜雪原万里 都是惊喜",
    "descriptionPgc": "雪原万里，都是大自然给予的惊喜。\n太阳从南半球回归，\n温暖也在不远之日。\n长路浩浩荡荡，\n万事皆可期待。\n你也一定要站在自己所热爱的世界里，\n闪闪发亮。",
    "remark": "",
    "ifLimitVideo": false,
    "searchWeight": 0,
    "idx": 0,
    "date": 1589517738000,
    "descriptionEditor": "",
    "collected": false,
    "reallyCollected": false,
    "played": false
  },
  "id": 0,
  "adIndex": -1
} 
*/

  String? type;
  FollowItemListDataItemListData? data;
  int? id;
  int? adIndex;

  FollowItemListDataItemList({
    this.type,
    this.data,
    this.id,
    this.adIndex,
  });
  FollowItemListDataItemList.fromJson(Map<String, dynamic> json) {
    type = json["type"]?.toString();
    data = (json["data"] != null)
        ? FollowItemListDataItemListData.fromJson(json["data"])
        : null;
    id = json["id"]?.toInt();
    adIndex = json["adIndex"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["type"] = type;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["id"] = id;
    data["adIndex"] = adIndex;
    return data;
  }
}

class FollowItemListDataHeaderFollow {
/*
{
  "itemType": "author",
  "itemId": 3443,
  "followed": false
} 
*/

  String? itemType;
  int? itemId;
  bool? followed;

  FollowItemListDataHeaderFollow({
    this.itemType,
    this.itemId,
    this.followed,
  });
  FollowItemListDataHeaderFollow.fromJson(Map<String, dynamic> json) {
    itemType = json["itemType"]?.toString();
    itemId = json["itemId"]?.toInt();
    followed = json["followed"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["itemType"] = itemType;
    data["itemId"] = itemId;
    data["followed"] = followed;
    return data;
  }
}

class FollowItemListDataHeader {
/*
{
  "id": 3443,
  "icon": "http://img.kaiyanapp.com/97f314dfee63a00107e177a174858303.png?imageMogr2/quality/60/format/jpg",
  "iconType": "round",
  "title": "姚舜不二",
  "description": "93年 62国\n独立跳伞员/滑翔伞员 水肺教练\n冲浪手 旅行体验师\n",
  "actionUrl": "eyepetizer://pgc/detail/3443/?title=%E5%A7%9A%E8%88%9C%E4%B8%8D%E4%BA%8C&userType=PGC&tabIndex=1",
  "follow": {
    "itemType": "author",
    "itemId": 3443,
    "followed": false
  },
  "ifPgc": true,
  "uid": 0,
  "ifShowNotificationIcon": false,
  "expert": false
} 
*/

  int? id;
  String? icon;
  String? iconType;
  String? title;
  String? description;
  String? actionUrl;
  FollowItemListDataHeaderFollow? follow;
  bool? ifPgc;
  int? uid;
  bool? ifShowNotificationIcon;
  bool? expert;

  FollowItemListDataHeader({
    this.id,
    this.icon,
    this.iconType,
    this.title,
    this.description,
    this.actionUrl,
    this.follow,
    this.ifPgc,
    this.uid,
    this.ifShowNotificationIcon,
    this.expert,
  });
  FollowItemListDataHeader.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    icon = json["icon"]?.toString();
    iconType = json["iconType"]?.toString();
    title = json["title"]?.toString();
    description = json["description"]?.toString();
    actionUrl = json["actionUrl"]?.toString();
    follow = (json["follow"] != null)
        ? FollowItemListDataHeaderFollow.fromJson(json["follow"])
        : null;
    ifPgc = json["ifPgc"];
    uid = json["uid"]?.toInt();
    ifShowNotificationIcon = json["ifShowNotificationIcon"];
    expert = json["expert"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["icon"] = icon;
    data["iconType"] = iconType;
    data["title"] = title;
    data["description"] = description;
    data["actionUrl"] = actionUrl;
    if (follow != null) {
      data["follow"] = follow!.toJson();
    }
    data["ifPgc"] = ifPgc;
    data["uid"] = uid;
    data["ifShowNotificationIcon"] = ifShowNotificationIcon;
    data["expert"] = expert;
    return data;
  }
}

class FollowItemListData {
/*
{
  "dataType": "ItemCollection",
  "header": {
    "id": 3443,
    "icon": "http://img.kaiyanapp.com/97f314dfee63a00107e177a174858303.png?imageMogr2/quality/60/format/jpg",
    "iconType": "round",
    "title": "姚舜不二",
    "description": "93年 62国\n独立跳伞员/滑翔伞员 水肺教练\n冲浪手 旅行体验师\n",
    "actionUrl": "eyepetizer://pgc/detail/3443/?title=%E5%A7%9A%E8%88%9C%E4%B8%8D%E4%BA%8C&userType=PGC&tabIndex=1",
    "follow": {
      "itemType": "author",
      "itemId": 3443,
      "followed": false
    },
    "ifPgc": true,
    "uid": 0,
    "ifShowNotificationIcon": false,
    "expert": false
  },
  "itemList": [
    {
      "type": "video",
      "data": {
        "dataType": "VideoBeanForClient",
        "id": 194586,
        "title": "Jeep自驾｜雪原万里 都是惊喜",
        "description": "雪原万里，都是大自然给予的惊喜。\n太阳从南半球回归，\n温暖也在不远之日。\n长路浩浩荡荡，\n万事皆可期待。\n你也一定要站在自己所热爱的世界里，\n闪闪发亮。",
        "library": "DEFAULT",
        "tags": [
          {
            "id": 10,
            "name": "跟着开眼看世界",
            "actionUrl": "eyepetizer://tag/10/?title=%E8%B7%9F%E7%9D%80%E5%BC%80%E7%9C%BC%E7%9C%8B%E4%B8%96%E7%95%8C",
            "desc": "去你想去的地方，发现世界的美",
            "bgPicture": "http://img.kaiyanapp.com/7ea328a893aa1f092b9328a53494a267.png?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/50dab5468ecd2dbe5eb99dab5d608a0a.jpeg?imageMogr2/quality/60/format/jpg",
            "tagRecType": "IMPORTANT",
            "haveReward": false,
            "ifNewest": false,
            "communityIndex": 14
          }
        ],
        "consumption": {
          "collectionCount": 30,
          "shareCount": 21,
          "replyCount": 1,
          "realCollectionCount": 0
        },
        "resourceType": "video",
        "category": "旅行",
        "author": {
          "id": 3443,
          "icon": "http://img.kaiyanapp.com/97f314dfee63a00107e177a174858303.png?imageMogr2/quality/60/format/jpg",
          "name": "姚舜不二",
          "description": "93年 62国\n独立跳伞员/滑翔伞员 水肺教练\n冲浪手 旅行体验师\n",
          "link": "",
          "latestReleaseTime": 1589517738000,
          "videoNum": 14,
          "follow": {
            "itemType": "author",
            "itemId": 3443,
            "followed": false
          },
          "shield": {
            "itemType": "author",
            "itemId": 3443,
            "shielded": false
          },
          "approvedNotReadyVideoCount": 0,
          "ifPgc": true,
          "recSort": 0,
          "expert": false
        },
        "cover": {
          "feed": "http://img.kaiyanapp.com/ef8aab4eb02d7169d98acfd1e4e8d1e4.png?imageMogr2/quality/60/format/jpg",
          "detail": "http://img.kaiyanapp.com/ef8aab4eb02d7169d98acfd1e4e8d1e4.png?imageMogr2/quality/60/format/jpg",
          "blurred": "http://img.kaiyanapp.com/a7b8e9927e9e0bcbf9b8755f798a4c25.jpeg?imageMogr2/quality/60/format/jpg"
        },
        "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=194586&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
        "duration": 121,
        "webUrl": {
          "raw": "http://www.eyepetizer.net/detail.html?vid=194586",
          "forWeibo": "http://www.eyepetizer.net/detail.html?vid=194586&resourceType=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
        },
        "releaseTime": 1589517738000,
        "ad": false,
        "type": "NORMAL",
        "titlePgc": "Jeep自驾｜雪原万里 都是惊喜",
        "descriptionPgc": "雪原万里，都是大自然给予的惊喜。\n太阳从南半球回归，\n温暖也在不远之日。\n长路浩浩荡荡，\n万事皆可期待。\n你也一定要站在自己所热爱的世界里，\n闪闪发亮。",
        "remark": "",
        "ifLimitVideo": false,
        "searchWeight": 0,
        "idx": 0,
        "date": 1589517738000,
        "descriptionEditor": "",
        "collected": false,
        "reallyCollected": false,
        "played": false
      },
      "id": 0,
      "adIndex": -1
    }
  ],
  "count": 5
} 
*/

  String? dataType;
  FollowItemListDataHeader? header;
  List<FollowItemListDataItemList?>? itemList;
  int? count;

  FollowItemListData({
    this.dataType,
    this.header,
    this.itemList,
    this.count,
  });
  FollowItemListData.fromJson(Map<String, dynamic> json) {
    dataType = json["dataType"]?.toString();
    header = (json["header"] != null)
        ? FollowItemListDataHeader.fromJson(json["header"])
        : null;
    if (json["itemList"] != null) {
      final v = json["itemList"];
      final arr0 = <FollowItemListDataItemList>[];
      // 判断类型
      v.forEach((v) {
        if (v["type"] == "video") {
          arr0.add(FollowItemListDataItemList.fromJson(v));
        }
      });
      itemList = arr0;
    }
    count = json["count"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["dataType"] = dataType;
    if (header != null) {
      data["header"] = header!.toJson();
    }
    if (itemList != null) {
      final v = itemList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["itemList"] = arr0;
    }
    data["count"] = count;
    return data;
  }
}

class FollowItemList {
/*
{
  "type": "videoCollectionWithBrief",
  "data": {
    "dataType": "ItemCollection",
    "header": {
      "id": 3443,
      "icon": "http://img.kaiyanapp.com/97f314dfee63a00107e177a174858303.png?imageMogr2/quality/60/format/jpg",
      "iconType": "round",
      "title": "姚舜不二",
      "description": "93年 62国\n独立跳伞员/滑翔伞员 水肺教练\n冲浪手 旅行体验师\n",
      "actionUrl": "eyepetizer://pgc/detail/3443/?title=%E5%A7%9A%E8%88%9C%E4%B8%8D%E4%BA%8C&userType=PGC&tabIndex=1",
      "follow": {
        "itemType": "author",
        "itemId": 3443,
        "followed": false
      },
      "ifPgc": true,
      "uid": 0,
      "ifShowNotificationIcon": false,
      "expert": false
    },
    "itemList": [
      {
        "type": "video",
        "data": {
          "dataType": "VideoBeanForClient",
          "id": 194586,
          "title": "Jeep自驾｜雪原万里 都是惊喜",
          "description": "雪原万里，都是大自然给予的惊喜。\n太阳从南半球回归，\n温暖也在不远之日。\n长路浩浩荡荡，\n万事皆可期待。\n你也一定要站在自己所热爱的世界里，\n闪闪发亮。",
          "library": "DEFAULT",
          "tags": [
            {
              "id": 10,
              "name": "跟着开眼看世界",
              "actionUrl": "eyepetizer://tag/10/?title=%E8%B7%9F%E7%9D%80%E5%BC%80%E7%9C%BC%E7%9C%8B%E4%B8%96%E7%95%8C",
              "desc": "去你想去的地方，发现世界的美",
              "bgPicture": "http://img.kaiyanapp.com/7ea328a893aa1f092b9328a53494a267.png?imageMogr2/quality/60/format/jpg",
              "headerImage": "http://img.kaiyanapp.com/50dab5468ecd2dbe5eb99dab5d608a0a.jpeg?imageMogr2/quality/60/format/jpg",
              "tagRecType": "IMPORTANT",
              "haveReward": false,
              "ifNewest": false,
              "communityIndex": 14
            }
          ],
          "consumption": {
            "collectionCount": 30,
            "shareCount": 21,
            "replyCount": 1,
            "realCollectionCount": 0
          },
          "resourceType": "video",
          "category": "旅行",
          "author": {
            "id": 3443,
            "icon": "http://img.kaiyanapp.com/97f314dfee63a00107e177a174858303.png?imageMogr2/quality/60/format/jpg",
            "name": "姚舜不二",
            "description": "93年 62国\n独立跳伞员/滑翔伞员 水肺教练\n冲浪手 旅行体验师\n",
            "link": "",
            "latestReleaseTime": 1589517738000,
            "videoNum": 14,
            "follow": {
              "itemType": "author",
              "itemId": 3443,
              "followed": false
            },
            "shield": {
              "itemType": "author",
              "itemId": 3443,
              "shielded": false
            },
            "approvedNotReadyVideoCount": 0,
            "ifPgc": true,
            "recSort": 0,
            "expert": false
          },
          "cover": {
            "feed": "http://img.kaiyanapp.com/ef8aab4eb02d7169d98acfd1e4e8d1e4.png?imageMogr2/quality/60/format/jpg",
            "detail": "http://img.kaiyanapp.com/ef8aab4eb02d7169d98acfd1e4e8d1e4.png?imageMogr2/quality/60/format/jpg",
            "blurred": "http://img.kaiyanapp.com/a7b8e9927e9e0bcbf9b8755f798a4c25.jpeg?imageMogr2/quality/60/format/jpg"
          },
          "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=194586&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
          "duration": 121,
          "webUrl": {
            "raw": "http://www.eyepetizer.net/detail.html?vid=194586",
            "forWeibo": "http://www.eyepetizer.net/detail.html?vid=194586&resourceType=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
          },
          "releaseTime": 1589517738000,
          "ad": false,
          "type": "NORMAL",
          "titlePgc": "Jeep自驾｜雪原万里 都是惊喜",
          "descriptionPgc": "雪原万里，都是大自然给予的惊喜。\n太阳从南半球回归，\n温暖也在不远之日。\n长路浩浩荡荡，\n万事皆可期待。\n你也一定要站在自己所热爱的世界里，\n闪闪发亮。",
          "remark": "",
          "ifLimitVideo": false,
          "searchWeight": 0,
          "idx": 0,
          "date": 1589517738000,
          "descriptionEditor": "",
          "collected": false,
          "reallyCollected": false,
          "played": false
        },
        "id": 0,
        "adIndex": -1
      }
    ],
    "count": 5
  },
  "id": 0,
  "adIndex": -1
} 
*/

  String? type;
  FollowItemListData? data;
  int? id;
  int? adIndex;

  FollowItemList({
    this.type,
    this.data,
    this.id,
    this.adIndex,
  });
  FollowItemList.fromJson(Map<String, dynamic> json) {
    type = json["type"]?.toString();
    data = (json["data"] != null)
        ? FollowItemListData.fromJson(json["data"])
        : null;
    id = json["id"]?.toInt();
    adIndex = json["adIndex"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["type"] = type;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["id"] = id;
    data["adIndex"] = adIndex;
    return data;
  }
}

class Follow {
/*
{
  "itemList": [
    {
      "type": "videoCollectionWithBrief",
      "data": {
        "dataType": "ItemCollection",
        "header": {
          "id": 3443,
          "icon": "http://img.kaiyanapp.com/97f314dfee63a00107e177a174858303.png?imageMogr2/quality/60/format/jpg",
          "iconType": "round",
          "title": "姚舜不二",
          "description": "93年 62国\n独立跳伞员/滑翔伞员 水肺教练\n冲浪手 旅行体验师\n",
          "actionUrl": "eyepetizer://pgc/detail/3443/?title=%E5%A7%9A%E8%88%9C%E4%B8%8D%E4%BA%8C&userType=PGC&tabIndex=1",
          "follow": {
            "itemType": "author",
            "itemId": 3443,
            "followed": false
          },
          "ifPgc": true,
          "uid": 0,
          "ifShowNotificationIcon": false,
          "expert": false
        },
        "itemList": [
          {
            "type": "video",
            "data": {
              "dataType": "VideoBeanForClient",
              "id": 194586,
              "title": "Jeep自驾｜雪原万里 都是惊喜",
              "description": "雪原万里，都是大自然给予的惊喜。\n太阳从南半球回归，\n温暖也在不远之日。\n长路浩浩荡荡，\n万事皆可期待。\n你也一定要站在自己所热爱的世界里，\n闪闪发亮。",
              "library": "DEFAULT",
              "tags": [
                {
                  "id": 10,
                  "name": "跟着开眼看世界",
                  "actionUrl": "eyepetizer://tag/10/?title=%E8%B7%9F%E7%9D%80%E5%BC%80%E7%9C%BC%E7%9C%8B%E4%B8%96%E7%95%8C",
                  "desc": "去你想去的地方，发现世界的美",
                  "bgPicture": "http://img.kaiyanapp.com/7ea328a893aa1f092b9328a53494a267.png?imageMogr2/quality/60/format/jpg",
                  "headerImage": "http://img.kaiyanapp.com/50dab5468ecd2dbe5eb99dab5d608a0a.jpeg?imageMogr2/quality/60/format/jpg",
                  "tagRecType": "IMPORTANT",
                  "haveReward": false,
                  "ifNewest": false,
                  "communityIndex": 14
                }
              ],
              "consumption": {
                "collectionCount": 30,
                "shareCount": 21,
                "replyCount": 1,
                "realCollectionCount": 0
              },
              "resourceType": "video",
              "category": "旅行",
              "author": {
                "id": 3443,
                "icon": "http://img.kaiyanapp.com/97f314dfee63a00107e177a174858303.png?imageMogr2/quality/60/format/jpg",
                "name": "姚舜不二",
                "description": "93年 62国\n独立跳伞员/滑翔伞员 水肺教练\n冲浪手 旅行体验师\n",
                "link": "",
                "latestReleaseTime": 1589517738000,
                "videoNum": 14,
                "follow": {
                  "itemType": "author",
                  "itemId": 3443,
                  "followed": false
                },
                "shield": {
                  "itemType": "author",
                  "itemId": 3443,
                  "shielded": false
                },
                "approvedNotReadyVideoCount": 0,
                "ifPgc": true,
                "recSort": 0,
                "expert": false
              },
              "cover": {
                "feed": "http://img.kaiyanapp.com/ef8aab4eb02d7169d98acfd1e4e8d1e4.png?imageMogr2/quality/60/format/jpg",
                "detail": "http://img.kaiyanapp.com/ef8aab4eb02d7169d98acfd1e4e8d1e4.png?imageMogr2/quality/60/format/jpg",
                "blurred": "http://img.kaiyanapp.com/a7b8e9927e9e0bcbf9b8755f798a4c25.jpeg?imageMogr2/quality/60/format/jpg"
              },
              "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=194586&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
              "duration": 121,
              "webUrl": {
                "raw": "http://www.eyepetizer.net/detail.html?vid=194586",
                "forWeibo": "http://www.eyepetizer.net/detail.html?vid=194586&resourceType=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
              },
              "releaseTime": 1589517738000,
              "ad": false,
              "type": "NORMAL",
              "titlePgc": "Jeep自驾｜雪原万里 都是惊喜",
              "descriptionPgc": "雪原万里，都是大自然给予的惊喜。\n太阳从南半球回归，\n温暖也在不远之日。\n长路浩浩荡荡，\n万事皆可期待。\n你也一定要站在自己所热爱的世界里，\n闪闪发亮。",
              "remark": "",
              "ifLimitVideo": false,
              "searchWeight": 0,
              "idx": 0,
              "date": 1589517738000,
              "descriptionEditor": "",
              "collected": false,
              "reallyCollected": false,
              "played": false
            },
            "id": 0,
            "adIndex": -1
          }
        ],
        "count": 5
      },
      "id": 0,
      "adIndex": -1
    }
  ],
  "count": 4,
  "total": 0,
  "nextPageUrl": "https://baobab.kaiyanapp.com/api/v4/tabs/follow?start=2&num=2&follow=false&startId=0",
  "adExist": false,
  "refreshCount": 0,
  "lastStartId": 0
} 
*/

  List<FollowItemList?>? itemList;
  int? count;
  int? total;
  String? nextPageUrl;
  bool? adExist;
  int? refreshCount;
  int? lastStartId;

  Follow({
    this.itemList,
    this.count,
    this.total,
    this.nextPageUrl,
    this.adExist,
    this.refreshCount,
    this.lastStartId,
  });
  Follow.fromJson(Map<String, dynamic> json) {
    if (json["itemList"] != null) {
      final v = json["itemList"];
      final arr0 = <FollowItemList>[];
      v.forEach((v) {
        if (v["type"] == "videoCollectionWithBrief") {
          arr0.add(FollowItemList.fromJson(v));
        }
      });
      itemList = arr0;
    }
    count = json["count"]?.toInt();
    total = json["total"]?.toInt();
    nextPageUrl = json["nextPageUrl"]?.toString();
    adExist = json["adExist"];
    refreshCount = json["refreshCount"]?.toInt();
    lastStartId = json["lastStartId"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (itemList != null) {
      final v = itemList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["itemList"] = arr0;
    }
    data["count"] = count;
    data["total"] = total;
    data["nextPageUrl"] = nextPageUrl;
    data["adExist"] = adExist;
    data["refreshCount"] = refreshCount;
    data["lastStartId"] = lastStartId;
    return data;
  }
}
