///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ReelItemListData {
/*
{
  "dataType": "Banner",
  "id": 650,
  "title": "",
  "description": "",
  "image": "http://img.kaiyanapp.com/dfe45c520f5c7d9c2693e8ace63e67a4.png?imageMogr2/quality/60/format/jpg",
  "actionUrl": "eyepetizer://webview/?title=%E8%9F%B9%E8%9F%B9%E4%BD%A0%E5%8F%88%E8%82%A5%E6%9D%A5%E4%BA%86%EF%BC%8C%E6%88%91%E7%AD%89%E4%BD%A0%E4%B8%80%E5%B9%B4%E4%BA%86%EF%BC%81&url=http%3A%2F%2Fwww.eyepetizer.net%2Fvideos_article.html%3Fnid%3D650%26shareable%3Dtrue"
} 
*/

  String? dataType;
  int? id;
  String? title;
  String? description;
  String? image;
  String? actionUrl;

  ReelItemListData({
    this.dataType,
    this.id,
    this.title,
    this.description,
    this.image,
    this.actionUrl,
  });
  ReelItemListData.fromJson(Map<String, dynamic> json) {
    dataType = json["dataType"]?.toString();
    id = json["id"]?.toInt();
    title = json["title"]?.toString();
    description = json["description"]?.toString();
    image = json["image"]?.toString();
    actionUrl = json["actionUrl"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["dataType"] = dataType;
    data["id"] = id;
    data["title"] = title;
    data["description"] = description;
    data["image"] = image;
    data["actionUrl"] = actionUrl;
    return data;
  }
}

class ReelItemList {
/*
{
  "type": "banner2",
  "data": {
    "dataType": "Banner",
    "id": 650,
    "title": "",
    "description": "",
    "image": "http://img.kaiyanapp.com/dfe45c520f5c7d9c2693e8ace63e67a4.png?imageMogr2/quality/60/format/jpg",
    "actionUrl": "eyepetizer://webview/?title=%E8%9F%B9%E8%9F%B9%E4%BD%A0%E5%8F%88%E8%82%A5%E6%9D%A5%E4%BA%86%EF%BC%8C%E6%88%91%E7%AD%89%E4%BD%A0%E4%B8%80%E5%B9%B4%E4%BA%86%EF%BC%81&url=http%3A%2F%2Fwww.eyepetizer.net%2Fvideos_article.html%3Fnid%3D650%26shareable%3Dtrue"
  },
  "id": 0,
  "adIndex": -1
} 
*/

  String? type;
  ReelItemListData? data;
  int? id;
  int? adIndex;

  ReelItemList({
    this.type,
    this.data,
    this.id,
    this.adIndex,
  });
  ReelItemList.fromJson(Map<String, dynamic> json) {
    type = json["type"]?.toString();
    data =
        (json["data"] != null) ? ReelItemListData.fromJson(json["data"]) : null;
    id = json["id"]?.toInt();
    adIndex = json["adIndex"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["type"] = type;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["id"] = id;
    data["adIndex"] = adIndex;
    return data;
  }
}

class Reel {
/*
{
  "itemList": [
    {
      "type": "banner2",
      "data": {
        "dataType": "Banner",
        "id": 650,
        "title": "",
        "description": "",
        "image": "http://img.kaiyanapp.com/dfe45c520f5c7d9c2693e8ace63e67a4.png?imageMogr2/quality/60/format/jpg",
        "actionUrl": "eyepetizer://webview/?title=%E8%9F%B9%E8%9F%B9%E4%BD%A0%E5%8F%88%E8%82%A5%E6%9D%A5%E4%BA%86%EF%BC%8C%E6%88%91%E7%AD%89%E4%BD%A0%E4%B8%80%E5%B9%B4%E4%BA%86%EF%BC%81&url=http%3A%2F%2Fwww.eyepetizer.net%2Fvideos_article.html%3Fnid%3D650%26shareable%3Dtrue"
      },
      "id": 0,
      "adIndex": -1
    }
  ],
  "count": 10,
  "total": 0,
  "nextPageUrl": "https://baobab.kaiyanapp.com/api/v3/specialTopics?start=10&num=10",
  "adExist": false
} 
*/

  List<ReelItemList?>? itemList;
  int? count;
  int? total;
  String? nextPageUrl;
  bool? adExist;

  Reel({
    this.itemList,
    this.count,
    this.total,
    this.nextPageUrl,
    this.adExist,
  });
  Reel.fromJson(Map<String, dynamic> json) {
    if (json["itemList"] != null) {
      final v = json["itemList"];
      final arr0 = <ReelItemList>[];
      v.forEach((v) {
        arr0.add(ReelItemList.fromJson(v));
      });
      itemList = arr0;
    }
    count = json["count"]?.toInt();
    total = json["total"]?.toInt();
    nextPageUrl = json["nextPageUrl"]?.toString();
    adExist = json["adExist"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (itemList != null) {
      final v = itemList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["itemList"] = arr0;
    }
    data["count"] = count;
    data["total"] = total;
    data["nextPageUrl"] = nextPageUrl;
    data["adExist"] = adExist;
    return data;
  }
}
