///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ReelInfoItemListDataContentDataPlayInfoUrlList {
/*
{
  "name": "aliyun",
  "url": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=173057&resourceType=video&editionType=high&source=aliyun&playUrlType=url_oss&udid=",
  "size": 31297838
} 
*/

  String? name;
  String? url;
  int? size;

  ReelInfoItemListDataContentDataPlayInfoUrlList({
    this.name,
    this.url,
    this.size,
  });
  ReelInfoItemListDataContentDataPlayInfoUrlList.fromJson(
      Map<String, dynamic> json) {
    name = json["name"]?.toString();
    url = json["url"]?.toString();
    size = json["size"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["name"] = name;
    data["url"] = url;
    data["size"] = size;
    return data;
  }
}

class ReelInfoItemListDataContentDataPlayInfo {
/*
{
  "height": 720,
  "width": 1280,
  "urlList": [
    {
      "name": "aliyun",
      "url": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=173057&resourceType=video&editionType=high&source=aliyun&playUrlType=url_oss&udid=",
      "size": 31297838
    }
  ],
  "name": "高清",
  "type": "high",
  "url": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=173057&resourceType=video&editionType=high&source=aliyun&playUrlType=url_oss&udid="
} 
*/

  int? height;
  int? width;
  List<ReelInfoItemListDataContentDataPlayInfoUrlList?>? urlList;
  String? name;
  String? type;
  String? url;

  ReelInfoItemListDataContentDataPlayInfo({
    this.height,
    this.width,
    this.urlList,
    this.name,
    this.type,
    this.url,
  });
  ReelInfoItemListDataContentDataPlayInfo.fromJson(Map<String, dynamic> json) {
    height = json["height"]?.toInt();
    width = json["width"]?.toInt();
    if (json["urlList"] != null) {
      final v = json["urlList"];
      final arr0 = <ReelInfoItemListDataContentDataPlayInfoUrlList>[];
      v.forEach((v) {
        arr0.add(ReelInfoItemListDataContentDataPlayInfoUrlList.fromJson(v));
      });
      urlList = arr0;
    }
    name = json["name"]?.toString();
    type = json["type"]?.toString();
    url = json["url"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["height"] = height;
    data["width"] = width;
    if (urlList != null) {
      final v = urlList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["urlList"] = arr0;
    }
    data["name"] = name;
    data["type"] = type;
    data["url"] = url;
    return data;
  }
}

class ReelInfoItemListDataContentDataWebUrl {
/*
{
  "raw": "http://www.eyepetizer.net/detail.html?vid=173057",
  "forWeibo": "http://www.eyepetizer.net/detail.html?vid=173057&resourceType=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
} 
*/

  String? raw;
  String? forWeibo;

  ReelInfoItemListDataContentDataWebUrl({
    this.raw,
    this.forWeibo,
  });
  ReelInfoItemListDataContentDataWebUrl.fromJson(Map<String, dynamic> json) {
    raw = json["raw"]?.toString();
    forWeibo = json["forWeibo"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["raw"] = raw;
    data["forWeibo"] = forWeibo;
    return data;
  }
}

class ReelInfoItemListDataContentDataCover {
/*
{
  "feed": "http://img.kaiyanapp.com/a078fc3c91bb046939de69e10932cc1f.jpeg?imageMogr2/quality/60/format/jpg",
  "detail": "http://img.kaiyanapp.com/a078fc3c91bb046939de69e10932cc1f.jpeg?imageMogr2/quality/60/format/jpg",
  "blurred": "http://img.kaiyanapp.com/6eef22acd07b3df580a14982d6d99fce.jpeg?imageMogr2/quality/60/format/jpg",
  "homepage": "http://img.kaiyanapp.com/a078fc3c91bb046939de69e10932cc1f.jpeg?imageView2/1/w/720/h/560/format/jpg/q/75|watermark/1/image/aHR0cDovL2ltZy5rYWl5YW5hcHAuY29tL2JsYWNrXzMwLnBuZw==/dissolve/100/gravity/Center/dx/0/dy/0|imageslim"
} 
*/

  String? feed;
  String? detail;
  String? blurred;
  String? homepage;

  ReelInfoItemListDataContentDataCover({
    this.feed,
    this.detail,
    this.blurred,
    this.homepage,
  });
  ReelInfoItemListDataContentDataCover.fromJson(Map<String, dynamic> json) {
    feed = json["feed"]?.toString();
    detail = json["detail"]?.toString();
    blurred = json["blurred"]?.toString();
    homepage = json["homepage"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["feed"] = feed;
    data["detail"] = detail;
    data["blurred"] = blurred;
    data["homepage"] = homepage;
    return data;
  }
}

class ReelInfoItemListDataContentDataAuthorShield {
/*
{
  "itemType": "author",
  "itemId": 2170,
  "shielded": false
} 
*/

  String? itemType;
  int? itemId;
  bool? shielded;

  ReelInfoItemListDataContentDataAuthorShield({
    this.itemType,
    this.itemId,
    this.shielded,
  });
  ReelInfoItemListDataContentDataAuthorShield.fromJson(
      Map<String, dynamic> json) {
    itemType = json["itemType"]?.toString();
    itemId = json["itemId"]?.toInt();
    shielded = json["shielded"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["itemType"] = itemType;
    data["itemId"] = itemId;
    data["shielded"] = shielded;
    return data;
  }
}

class ReelInfoItemListDataContentDataAuthorFollow {
/*
{
  "itemType": "author",
  "itemId": 2170,
  "followed": false
} 
*/

  String? itemType;
  int? itemId;
  bool? followed;

  ReelInfoItemListDataContentDataAuthorFollow({
    this.itemType,
    this.itemId,
    this.followed,
  });
  ReelInfoItemListDataContentDataAuthorFollow.fromJson(
      Map<String, dynamic> json) {
    itemType = json["itemType"]?.toString();
    itemId = json["itemId"]?.toInt();
    followed = json["followed"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["itemType"] = itemType;
    data["itemId"] = itemId;
    data["followed"] = followed;
    return data;
  }
}

class ReelInfoItemListDataContentDataAuthor {
/*
{
  "id": 2170,
  "icon": "http://img.kaiyanapp.com/482c741c06644f5566c7218096dbaf26.jpeg",
  "name": "全球动画精选",
  "description": "我们精选全球最好看的动画短片，有趣的人永远不缺童心。",
  "link": "",
  "latestReleaseTime": 1634369080000,
  "videoNum": 1304,
  "follow": {
    "itemType": "author",
    "itemId": 2170,
    "followed": false
  },
  "shield": {
    "itemType": "author",
    "itemId": 2170,
    "shielded": false
  },
  "approvedNotReadyVideoCount": 0,
  "ifPgc": true,
  "recSort": 0,
  "expert": false
} 
*/

  int? id;
  String? icon;
  String? name;
  String? description;
  String? link;
  int? latestReleaseTime;
  int? videoNum;
  ReelInfoItemListDataContentDataAuthorFollow? follow;
  ReelInfoItemListDataContentDataAuthorShield? shield;
  int? approvedNotReadyVideoCount;
  bool? ifPgc;
  int? recSort;
  bool? expert;

  ReelInfoItemListDataContentDataAuthor({
    this.id,
    this.icon,
    this.name,
    this.description,
    this.link,
    this.latestReleaseTime,
    this.videoNum,
    this.follow,
    this.shield,
    this.approvedNotReadyVideoCount,
    this.ifPgc,
    this.recSort,
    this.expert,
  });
  ReelInfoItemListDataContentDataAuthor.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    icon = json["icon"]?.toString();
    name = json["name"]?.toString();
    description = json["description"]?.toString();
    link = json["link"]?.toString();
    latestReleaseTime = json["latestReleaseTime"]?.toInt();
    videoNum = json["videoNum"]?.toInt();
    follow = (json["follow"] != null)
        ? ReelInfoItemListDataContentDataAuthorFollow.fromJson(json["follow"])
        : null;
    shield = (json["shield"] != null)
        ? ReelInfoItemListDataContentDataAuthorShield.fromJson(json["shield"])
        : null;
    approvedNotReadyVideoCount = json["approvedNotReadyVideoCount"]?.toInt();
    ifPgc = json["ifPgc"];
    recSort = json["recSort"]?.toInt();
    expert = json["expert"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["icon"] = icon;
    data["name"] = name;
    data["description"] = description;
    data["link"] = link;
    data["latestReleaseTime"] = latestReleaseTime;
    data["videoNum"] = videoNum;
    if (follow != null) {
      data["follow"] = follow!.toJson();
    }
    if (shield != null) {
      data["shield"] = shield!.toJson();
    }
    data["approvedNotReadyVideoCount"] = approvedNotReadyVideoCount;
    data["ifPgc"] = ifPgc;
    data["recSort"] = recSort;
    data["expert"] = expert;
    return data;
  }
}

class ReelInfoItemListDataContentDataProvider {
/*
{
  "name": "Vimeo",
  "alias": "vimeo",
  "icon": "http://img.kaiyanapp.com/c3ad630be461cbb081649c9e21d6cbe3.png"
} 
*/

  String? name;
  String? alias;
  String? icon;

  ReelInfoItemListDataContentDataProvider({
    this.name,
    this.alias,
    this.icon,
  });
  ReelInfoItemListDataContentDataProvider.fromJson(Map<String, dynamic> json) {
    name = json["name"]?.toString();
    alias = json["alias"]?.toString();
    icon = json["icon"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["name"] = name;
    data["alias"] = alias;
    data["icon"] = icon;
    return data;
  }
}

class ReelInfoItemListDataContentDataConsumption {
/*
{
  "collectionCount": 5113,
  "shareCount": 2588,
  "replyCount": 26,
  "realCollectionCount": 273
} 
*/

  int? collectionCount;
  int? shareCount;
  int? replyCount;
  int? realCollectionCount;

  ReelInfoItemListDataContentDataConsumption({
    this.collectionCount,
    this.shareCount,
    this.replyCount,
    this.realCollectionCount,
  });
  ReelInfoItemListDataContentDataConsumption.fromJson(
      Map<String, dynamic> json) {
    collectionCount = json["collectionCount"]?.toInt();
    shareCount = json["shareCount"]?.toInt();
    replyCount = json["replyCount"]?.toInt();
    realCollectionCount = json["realCollectionCount"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["collectionCount"] = collectionCount;
    data["shareCount"] = shareCount;
    data["replyCount"] = replyCount;
    data["realCollectionCount"] = realCollectionCount;
    return data;
  }
}

class ReelInfoItemListDataContentDataTags {
/*
{
  "id": 14,
  "name": "动画梦工厂",
  "actionUrl": "eyepetizer://tag/14/?title=%E5%8A%A8%E7%94%BB%E6%A2%A6%E5%B7%A5%E5%8E%82",
  "desc": "有趣的人永远不缺童心",
  "bgPicture": "http://img.kaiyanapp.com/afb9e7d7f061d10ade5ebcb524dc8679.jpeg?imageMogr2/quality/60/format/jpg",
  "headerImage": "http://img.kaiyanapp.com/f9eae3e0321fa1e99a7b38641b5536a2.jpeg?imageMogr2/quality/60/format/jpg",
  "tagRecType": "IMPORTANT",
  "haveReward": false,
  "ifNewest": false,
  "communityIndex": 0
} 
*/

  int? id;
  String? name;
  String? actionUrl;
  String? desc;
  String? bgPicture;
  String? headerImage;
  String? tagRecType;
  bool? haveReward;
  bool? ifNewest;
  int? communityIndex;

  ReelInfoItemListDataContentDataTags({
    this.id,
    this.name,
    this.actionUrl,
    this.desc,
    this.bgPicture,
    this.headerImage,
    this.tagRecType,
    this.haveReward,
    this.ifNewest,
    this.communityIndex,
  });
  ReelInfoItemListDataContentDataTags.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    name = json["name"]?.toString();
    actionUrl = json["actionUrl"]?.toString();
    desc = json["desc"]?.toString();
    bgPicture = json["bgPicture"]?.toString();
    headerImage = json["headerImage"]?.toString();
    tagRecType = json["tagRecType"]?.toString();
    haveReward = json["haveReward"];
    ifNewest = json["ifNewest"];
    communityIndex = json["communityIndex"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["actionUrl"] = actionUrl;
    data["desc"] = desc;
    data["bgPicture"] = bgPicture;
    data["headerImage"] = headerImage;
    data["tagRecType"] = tagRecType;
    data["haveReward"] = haveReward;
    data["ifNewest"] = ifNewest;
    data["communityIndex"] = communityIndex;
    return data;
  }
}

class ReelInfoItemListDataContentData {
/*
{
  "dataType": "VideoBeanForClient",
  "id": 173057,
  "title": "重阳节特辑 |  我的爷爷，是只「黑熊」",
  "description": "惠惠在搬家整理行李的时候，找到了爷爷心爱的黑熊纸镇，同时也是惠惠小时候最好的朋友：阿墨。虽然爷爷总是把纸镇收在玻璃柜裡，惠惠总是把阿墨当成玩伴带在身边，不论是洗澡、看书的时间、躲猫猫。阿墨好像参与惠惠所有的童年生活。From David Chao",
  "library": "DAILY",
  "tags": [
    {
      "id": 14,
      "name": "动画梦工厂",
      "actionUrl": "eyepetizer://tag/14/?title=%E5%8A%A8%E7%94%BB%E6%A2%A6%E5%B7%A5%E5%8E%82",
      "desc": "有趣的人永远不缺童心",
      "bgPicture": "http://img.kaiyanapp.com/afb9e7d7f061d10ade5ebcb524dc8679.jpeg?imageMogr2/quality/60/format/jpg",
      "headerImage": "http://img.kaiyanapp.com/f9eae3e0321fa1e99a7b38641b5536a2.jpeg?imageMogr2/quality/60/format/jpg",
      "tagRecType": "IMPORTANT",
      "haveReward": false,
      "ifNewest": false,
      "communityIndex": 0
    }
  ],
  "consumption": {
    "collectionCount": 5113,
    "shareCount": 2588,
    "replyCount": 26,
    "realCollectionCount": 273
  },
  "resourceType": "video",
  "provider": {
    "name": "Vimeo",
    "alias": "vimeo",
    "icon": "http://img.kaiyanapp.com/c3ad630be461cbb081649c9e21d6cbe3.png"
  },
  "category": "动画",
  "author": {
    "id": 2170,
    "icon": "http://img.kaiyanapp.com/482c741c06644f5566c7218096dbaf26.jpeg",
    "name": "全球动画精选",
    "description": "我们精选全球最好看的动画短片，有趣的人永远不缺童心。",
    "link": "",
    "latestReleaseTime": 1634369080000,
    "videoNum": 1304,
    "follow": {
      "itemType": "author",
      "itemId": 2170,
      "followed": false
    },
    "shield": {
      "itemType": "author",
      "itemId": 2170,
      "shielded": false
    },
    "approvedNotReadyVideoCount": 0,
    "ifPgc": true,
    "recSort": 0,
    "expert": false
  },
  "cover": {
    "feed": "http://img.kaiyanapp.com/a078fc3c91bb046939de69e10932cc1f.jpeg?imageMogr2/quality/60/format/jpg",
    "detail": "http://img.kaiyanapp.com/a078fc3c91bb046939de69e10932cc1f.jpeg?imageMogr2/quality/60/format/jpg",
    "blurred": "http://img.kaiyanapp.com/6eef22acd07b3df580a14982d6d99fce.jpeg?imageMogr2/quality/60/format/jpg",
    "homepage": "http://img.kaiyanapp.com/a078fc3c91bb046939de69e10932cc1f.jpeg?imageView2/1/w/720/h/560/format/jpg/q/75|watermark/1/image/aHR0cDovL2ltZy5rYWl5YW5hcHAuY29tL2JsYWNrXzMwLnBuZw==/dissolve/100/gravity/Center/dx/0/dy/0|imageslim"
  },
  "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=173057&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
  "duration": 428,
  "webUrl": {
    "raw": "http://www.eyepetizer.net/detail.html?vid=173057",
    "forWeibo": "http://www.eyepetizer.net/detail.html?vid=173057&resourceType=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
  },
  "releaseTime": 1570410008000,
  "playInfo": [
    {
      "height": 720,
      "width": 1280,
      "urlList": [
        {
          "name": "aliyun",
          "url": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=173057&resourceType=video&editionType=high&source=aliyun&playUrlType=url_oss&udid=",
          "size": 31297838
        }
      ],
      "name": "高清",
      "type": "high",
      "url": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=173057&resourceType=video&editionType=high&source=aliyun&playUrlType=url_oss&udid="
    }
  ],
  "ad": false,
  "type": "NORMAL",
  "ifLimitVideo": false,
  "searchWeight": 0,
  "idx": 0,
  "date": 1570410008000,
  "descriptionEditor": "惠惠在搬家整理行李的时候，找到了爷爷心爱的黑熊纸镇，同时也是惠惠小时候最好的朋友：阿墨。虽然爷爷总是把纸镇收在玻璃柜裡，惠惠总是把阿墨当成玩伴带在身边，不论是洗澡、看书的时间、躲猫猫。阿墨好像参与惠惠所有的童年生活。From David Chao",
  "collected": false,
  "reallyCollected": false,
  "played": false
} 
*/

  String? dataType;
  int? id;
  String? title;
  String? description;
  String? theLibrary;
  List<ReelInfoItemListDataContentDataTags?>? tags;
  ReelInfoItemListDataContentDataConsumption? consumption;
  String? resourceType;
  ReelInfoItemListDataContentDataProvider? provider;
  String? category;
  ReelInfoItemListDataContentDataAuthor? author;
  ReelInfoItemListDataContentDataCover? cover;
  String? playUrl;
  int? duration;
  ReelInfoItemListDataContentDataWebUrl? webUrl;
  int? releaseTime;
  List<ReelInfoItemListDataContentDataPlayInfo?>? playInfo;
  bool? ad;
  String? type;
  bool? ifLimitVideo;
  int? searchWeight;
  int? idx;
  int? date;
  String? descriptionEditor;
  bool? collected;
  bool? reallyCollected;
  bool? played;

  ReelInfoItemListDataContentData({
    this.dataType,
    this.id,
    this.title,
    this.description,
    this.theLibrary,
    this.tags,
    this.consumption,
    this.resourceType,
    this.provider,
    this.category,
    this.author,
    this.cover,
    this.playUrl,
    this.duration,
    this.webUrl,
    this.releaseTime,
    this.playInfo,
    this.ad,
    this.type,
    this.ifLimitVideo,
    this.searchWeight,
    this.idx,
    this.date,
    this.descriptionEditor,
    this.collected,
    this.reallyCollected,
    this.played,
  });
  ReelInfoItemListDataContentData.fromJson(Map<String, dynamic> json) {
    dataType = json["dataType"]?.toString();
    id = json["id"]?.toInt();
    title = json["title"]?.toString();
    description = json["description"]?.toString();
    theLibrary = json["library"]?.toString();
    if (json["tags"] != null) {
      final v = json["tags"];
      final arr0 = <ReelInfoItemListDataContentDataTags>[];
      v.forEach((v) {
        arr0.add(ReelInfoItemListDataContentDataTags.fromJson(v));
      });
      tags = arr0;
    }
    consumption = (json["consumption"] != null)
        ? ReelInfoItemListDataContentDataConsumption.fromJson(
            json["consumption"])
        : null;
    resourceType = json["resourceType"]?.toString();
    provider = (json["provider"] != null)
        ? ReelInfoItemListDataContentDataProvider.fromJson(json["provider"])
        : null;
    category = json["category"]?.toString();
    author = (json["author"] != null)
        ? ReelInfoItemListDataContentDataAuthor.fromJson(json["author"])
        : null;
    cover = (json["cover"] != null)
        ? ReelInfoItemListDataContentDataCover.fromJson(json["cover"])
        : null;
    playUrl = json["playUrl"]?.toString();
    duration = json["duration"]?.toInt();
    webUrl = (json["webUrl"] != null)
        ? ReelInfoItemListDataContentDataWebUrl.fromJson(json["webUrl"])
        : null;
    releaseTime = json["releaseTime"]?.toInt();
    if (json["playInfo"] != null) {
      final v = json["playInfo"];
      final arr0 = <ReelInfoItemListDataContentDataPlayInfo>[];
      v.forEach((v) {
        arr0.add(ReelInfoItemListDataContentDataPlayInfo.fromJson(v));
      });
      playInfo = arr0;
    }
    ad = json["ad"];
    type = json["type"]?.toString();
    ifLimitVideo = json["ifLimitVideo"];
    searchWeight = json["searchWeight"]?.toInt();
    idx = json["idx"]?.toInt();
    date = json["date"]?.toInt();
    descriptionEditor = json["descriptionEditor"]?.toString();
    collected = json["collected"];
    reallyCollected = json["reallyCollected"];
    played = json["played"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["dataType"] = dataType;
    data["id"] = id;
    data["title"] = title;
    data["description"] = description;
    data["library"] = theLibrary;
    if (tags != null) {
      final v = tags;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["tags"] = arr0;
    }
    if (consumption != null) {
      data["consumption"] = consumption!.toJson();
    }
    data["resourceType"] = resourceType;
    if (provider != null) {
      data["provider"] = provider!.toJson();
    }
    data["category"] = category;
    if (author != null) {
      data["author"] = author!.toJson();
    }
    if (cover != null) {
      data["cover"] = cover!.toJson();
    }
    data["playUrl"] = playUrl;
    data["duration"] = duration;
    if (webUrl != null) {
      data["webUrl"] = webUrl!.toJson();
    }
    data["releaseTime"] = releaseTime;
    if (playInfo != null) {
      final v = playInfo;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["playInfo"] = arr0;
    }
    data["ad"] = ad;
    data["type"] = type;
    data["ifLimitVideo"] = ifLimitVideo;
    data["searchWeight"] = searchWeight;
    data["idx"] = idx;
    data["date"] = date;
    data["descriptionEditor"] = descriptionEditor;
    data["collected"] = collected;
    data["reallyCollected"] = reallyCollected;
    data["played"] = played;
    return data;
  }
}

class ReelInfoItemListDataContent {
/*
{
  "type": "video",
  "data": {
    "dataType": "VideoBeanForClient",
    "id": 173057,
    "title": "重阳节特辑 |  我的爷爷，是只「黑熊」",
    "description": "惠惠在搬家整理行李的时候，找到了爷爷心爱的黑熊纸镇，同时也是惠惠小时候最好的朋友：阿墨。虽然爷爷总是把纸镇收在玻璃柜裡，惠惠总是把阿墨当成玩伴带在身边，不论是洗澡、看书的时间、躲猫猫。阿墨好像参与惠惠所有的童年生活。From David Chao",
    "library": "DAILY",
    "tags": [
      {
        "id": 14,
        "name": "动画梦工厂",
        "actionUrl": "eyepetizer://tag/14/?title=%E5%8A%A8%E7%94%BB%E6%A2%A6%E5%B7%A5%E5%8E%82",
        "desc": "有趣的人永远不缺童心",
        "bgPicture": "http://img.kaiyanapp.com/afb9e7d7f061d10ade5ebcb524dc8679.jpeg?imageMogr2/quality/60/format/jpg",
        "headerImage": "http://img.kaiyanapp.com/f9eae3e0321fa1e99a7b38641b5536a2.jpeg?imageMogr2/quality/60/format/jpg",
        "tagRecType": "IMPORTANT",
        "haveReward": false,
        "ifNewest": false,
        "communityIndex": 0
      }
    ],
    "consumption": {
      "collectionCount": 5113,
      "shareCount": 2588,
      "replyCount": 26,
      "realCollectionCount": 273
    },
    "resourceType": "video",
    "provider": {
      "name": "Vimeo",
      "alias": "vimeo",
      "icon": "http://img.kaiyanapp.com/c3ad630be461cbb081649c9e21d6cbe3.png"
    },
    "category": "动画",
    "author": {
      "id": 2170,
      "icon": "http://img.kaiyanapp.com/482c741c06644f5566c7218096dbaf26.jpeg",
      "name": "全球动画精选",
      "description": "我们精选全球最好看的动画短片，有趣的人永远不缺童心。",
      "link": "",
      "latestReleaseTime": 1634369080000,
      "videoNum": 1304,
      "follow": {
        "itemType": "author",
        "itemId": 2170,
        "followed": false
      },
      "shield": {
        "itemType": "author",
        "itemId": 2170,
        "shielded": false
      },
      "approvedNotReadyVideoCount": 0,
      "ifPgc": true,
      "recSort": 0,
      "expert": false
    },
    "cover": {
      "feed": "http://img.kaiyanapp.com/a078fc3c91bb046939de69e10932cc1f.jpeg?imageMogr2/quality/60/format/jpg",
      "detail": "http://img.kaiyanapp.com/a078fc3c91bb046939de69e10932cc1f.jpeg?imageMogr2/quality/60/format/jpg",
      "blurred": "http://img.kaiyanapp.com/6eef22acd07b3df580a14982d6d99fce.jpeg?imageMogr2/quality/60/format/jpg",
      "homepage": "http://img.kaiyanapp.com/a078fc3c91bb046939de69e10932cc1f.jpeg?imageView2/1/w/720/h/560/format/jpg/q/75|watermark/1/image/aHR0cDovL2ltZy5rYWl5YW5hcHAuY29tL2JsYWNrXzMwLnBuZw==/dissolve/100/gravity/Center/dx/0/dy/0|imageslim"
    },
    "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=173057&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
    "duration": 428,
    "webUrl": {
      "raw": "http://www.eyepetizer.net/detail.html?vid=173057",
      "forWeibo": "http://www.eyepetizer.net/detail.html?vid=173057&resourceType=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
    },
    "releaseTime": 1570410008000,
    "playInfo": [
      {
        "height": 720,
        "width": 1280,
        "urlList": [
          {
            "name": "aliyun",
            "url": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=173057&resourceType=video&editionType=high&source=aliyun&playUrlType=url_oss&udid=",
            "size": 31297838
          }
        ],
        "name": "高清",
        "type": "high",
        "url": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=173057&resourceType=video&editionType=high&source=aliyun&playUrlType=url_oss&udid="
      }
    ],
    "ad": false,
    "type": "NORMAL",
    "ifLimitVideo": false,
    "searchWeight": 0,
    "idx": 0,
    "date": 1570410008000,
    "descriptionEditor": "惠惠在搬家整理行李的时候，找到了爷爷心爱的黑熊纸镇，同时也是惠惠小时候最好的朋友：阿墨。虽然爷爷总是把纸镇收在玻璃柜裡，惠惠总是把阿墨当成玩伴带在身边，不论是洗澡、看书的时间、躲猫猫。阿墨好像参与惠惠所有的童年生活。From David Chao",
    "collected": false,
    "reallyCollected": false,
    "played": false
  },
  "id": 0,
  "adIndex": -1
} 
*/

  String? type;
  ReelInfoItemListDataContentData? data;
  int? id;
  int? adIndex;

  ReelInfoItemListDataContent({
    this.type,
    this.data,
    this.id,
    this.adIndex,
  });
  ReelInfoItemListDataContent.fromJson(Map<String, dynamic> json) {
    type = json["type"]?.toString();
    data = (json["data"] != null)
        ? ReelInfoItemListDataContentData.fromJson(json["data"])
        : null;
    id = json["id"]?.toInt();
    adIndex = json["adIndex"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["type"] = type;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["id"] = id;
    data["adIndex"] = adIndex;
    return data;
  }
}

class ReelInfoItemListDataHeader {
/*
{
  "id": 173057,
  "actionUrl": "eyepetizer://pgc/detail/2170/?title=%E5%85%A8%E7%90%83%E5%8A%A8%E7%94%BB%E7%B2%BE%E9%80%89&userType=PGC&tabIndex=1",
  "icon": "http://img.kaiyanapp.com/482c741c06644f5566c7218096dbaf26.jpeg",
  "iconType": "round",
  "time": 1570410008000,
  "showHateVideo": false,
  "followType": "author",
  "tagId": 0,
  "issuerName": "全球动画精选",
  "topShow": false
} 
*/

  int? id;
  String? actionUrl;
  String? icon;
  String? iconType;
  int? time;
  bool? showHateVideo;
  String? followType;
  int? tagId;
  String? issuerName;
  bool? topShow;

  ReelInfoItemListDataHeader({
    this.id,
    this.actionUrl,
    this.icon,
    this.iconType,
    this.time,
    this.showHateVideo,
    this.followType,
    this.tagId,
    this.issuerName,
    this.topShow,
  });
  ReelInfoItemListDataHeader.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    actionUrl = json["actionUrl"]?.toString();
    icon = json["icon"]?.toString();
    iconType = json["iconType"]?.toString();
    time = json["time"]?.toInt();
    showHateVideo = json["showHateVideo"];
    followType = json["followType"]?.toString();
    tagId = json["tagId"]?.toInt();
    issuerName = json["issuerName"]?.toString();
    topShow = json["topShow"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["actionUrl"] = actionUrl;
    data["icon"] = icon;
    data["iconType"] = iconType;
    data["time"] = time;
    data["showHateVideo"] = showHateVideo;
    data["followType"] = followType;
    data["tagId"] = tagId;
    data["issuerName"] = issuerName;
    data["topShow"] = topShow;
    return data;
  }
}

class ReelInfoItemListData {
/*
{
  "dataType": "FollowCard",
  "header": {
    "id": 173057,
    "actionUrl": "eyepetizer://pgc/detail/2170/?title=%E5%85%A8%E7%90%83%E5%8A%A8%E7%94%BB%E7%B2%BE%E9%80%89&userType=PGC&tabIndex=1",
    "icon": "http://img.kaiyanapp.com/482c741c06644f5566c7218096dbaf26.jpeg",
    "iconType": "round",
    "time": 1570410008000,
    "showHateVideo": false,
    "followType": "author",
    "tagId": 0,
    "issuerName": "全球动画精选",
    "topShow": false
  },
  "content": {
    "type": "video",
    "data": {
      "dataType": "VideoBeanForClient",
      "id": 173057,
      "title": "重阳节特辑 |  我的爷爷，是只「黑熊」",
      "description": "惠惠在搬家整理行李的时候，找到了爷爷心爱的黑熊纸镇，同时也是惠惠小时候最好的朋友：阿墨。虽然爷爷总是把纸镇收在玻璃柜裡，惠惠总是把阿墨当成玩伴带在身边，不论是洗澡、看书的时间、躲猫猫。阿墨好像参与惠惠所有的童年生活。From David Chao",
      "library": "DAILY",
      "tags": [
        {
          "id": 14,
          "name": "动画梦工厂",
          "actionUrl": "eyepetizer://tag/14/?title=%E5%8A%A8%E7%94%BB%E6%A2%A6%E5%B7%A5%E5%8E%82",
          "desc": "有趣的人永远不缺童心",
          "bgPicture": "http://img.kaiyanapp.com/afb9e7d7f061d10ade5ebcb524dc8679.jpeg?imageMogr2/quality/60/format/jpg",
          "headerImage": "http://img.kaiyanapp.com/f9eae3e0321fa1e99a7b38641b5536a2.jpeg?imageMogr2/quality/60/format/jpg",
          "tagRecType": "IMPORTANT",
          "haveReward": false,
          "ifNewest": false,
          "communityIndex": 0
        }
      ],
      "consumption": {
        "collectionCount": 5113,
        "shareCount": 2588,
        "replyCount": 26,
        "realCollectionCount": 273
      },
      "resourceType": "video",
      "provider": {
        "name": "Vimeo",
        "alias": "vimeo",
        "icon": "http://img.kaiyanapp.com/c3ad630be461cbb081649c9e21d6cbe3.png"
      },
      "category": "动画",
      "author": {
        "id": 2170,
        "icon": "http://img.kaiyanapp.com/482c741c06644f5566c7218096dbaf26.jpeg",
        "name": "全球动画精选",
        "description": "我们精选全球最好看的动画短片，有趣的人永远不缺童心。",
        "link": "",
        "latestReleaseTime": 1634369080000,
        "videoNum": 1304,
        "follow": {
          "itemType": "author",
          "itemId": 2170,
          "followed": false
        },
        "shield": {
          "itemType": "author",
          "itemId": 2170,
          "shielded": false
        },
        "approvedNotReadyVideoCount": 0,
        "ifPgc": true,
        "recSort": 0,
        "expert": false
      },
      "cover": {
        "feed": "http://img.kaiyanapp.com/a078fc3c91bb046939de69e10932cc1f.jpeg?imageMogr2/quality/60/format/jpg",
        "detail": "http://img.kaiyanapp.com/a078fc3c91bb046939de69e10932cc1f.jpeg?imageMogr2/quality/60/format/jpg",
        "blurred": "http://img.kaiyanapp.com/6eef22acd07b3df580a14982d6d99fce.jpeg?imageMogr2/quality/60/format/jpg",
        "homepage": "http://img.kaiyanapp.com/a078fc3c91bb046939de69e10932cc1f.jpeg?imageView2/1/w/720/h/560/format/jpg/q/75|watermark/1/image/aHR0cDovL2ltZy5rYWl5YW5hcHAuY29tL2JsYWNrXzMwLnBuZw==/dissolve/100/gravity/Center/dx/0/dy/0|imageslim"
      },
      "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=173057&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
      "duration": 428,
      "webUrl": {
        "raw": "http://www.eyepetizer.net/detail.html?vid=173057",
        "forWeibo": "http://www.eyepetizer.net/detail.html?vid=173057&resourceType=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
      },
      "releaseTime": 1570410008000,
      "playInfo": [
        {
          "height": 720,
          "width": 1280,
          "urlList": [
            {
              "name": "aliyun",
              "url": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=173057&resourceType=video&editionType=high&source=aliyun&playUrlType=url_oss&udid=",
              "size": 31297838
            }
          ],
          "name": "高清",
          "type": "high",
          "url": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=173057&resourceType=video&editionType=high&source=aliyun&playUrlType=url_oss&udid="
        }
      ],
      "ad": false,
      "type": "NORMAL",
      "ifLimitVideo": false,
      "searchWeight": 0,
      "idx": 0,
      "date": 1570410008000,
      "descriptionEditor": "惠惠在搬家整理行李的时候，找到了爷爷心爱的黑熊纸镇，同时也是惠惠小时候最好的朋友：阿墨。虽然爷爷总是把纸镇收在玻璃柜裡，惠惠总是把阿墨当成玩伴带在身边，不论是洗澡、看书的时间、躲猫猫。阿墨好像参与惠惠所有的童年生活。From David Chao",
      "collected": false,
      "reallyCollected": false,
      "played": false
    },
    "id": 0,
    "adIndex": -1
  }
} 
*/

  String? dataType;
  ReelInfoItemListDataHeader? header;
  ReelInfoItemListDataContent? content;

  ReelInfoItemListData({
    this.dataType,
    this.header,
    this.content,
  });
  ReelInfoItemListData.fromJson(Map<String, dynamic> json) {
    dataType = json["dataType"]?.toString();
    header = (json["header"] != null)
        ? ReelInfoItemListDataHeader.fromJson(json["header"])
        : null;
    content = (json["content"] != null)
        ? ReelInfoItemListDataContent.fromJson(json["content"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["dataType"] = dataType;
    if (header != null) {
      data["header"] = header!.toJson();
    }
    if (content != null) {
      data["content"] = content!.toJson();
    }
    return data;
  }
}

class ReelInfoItemList {
/*
{
  "type": "autoPlayFollowCard",
  "data": {
    "dataType": "FollowCard",
    "header": {
      "id": 173057,
      "actionUrl": "eyepetizer://pgc/detail/2170/?title=%E5%85%A8%E7%90%83%E5%8A%A8%E7%94%BB%E7%B2%BE%E9%80%89&userType=PGC&tabIndex=1",
      "icon": "http://img.kaiyanapp.com/482c741c06644f5566c7218096dbaf26.jpeg",
      "iconType": "round",
      "time": 1570410008000,
      "showHateVideo": false,
      "followType": "author",
      "tagId": 0,
      "issuerName": "全球动画精选",
      "topShow": false
    },
    "content": {
      "type": "video",
      "data": {
        "dataType": "VideoBeanForClient",
        "id": 173057,
        "title": "重阳节特辑 |  我的爷爷，是只「黑熊」",
        "description": "惠惠在搬家整理行李的时候，找到了爷爷心爱的黑熊纸镇，同时也是惠惠小时候最好的朋友：阿墨。虽然爷爷总是把纸镇收在玻璃柜裡，惠惠总是把阿墨当成玩伴带在身边，不论是洗澡、看书的时间、躲猫猫。阿墨好像参与惠惠所有的童年生活。From David Chao",
        "library": "DAILY",
        "tags": [
          {
            "id": 14,
            "name": "动画梦工厂",
            "actionUrl": "eyepetizer://tag/14/?title=%E5%8A%A8%E7%94%BB%E6%A2%A6%E5%B7%A5%E5%8E%82",
            "desc": "有趣的人永远不缺童心",
            "bgPicture": "http://img.kaiyanapp.com/afb9e7d7f061d10ade5ebcb524dc8679.jpeg?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/f9eae3e0321fa1e99a7b38641b5536a2.jpeg?imageMogr2/quality/60/format/jpg",
            "tagRecType": "IMPORTANT",
            "haveReward": false,
            "ifNewest": false,
            "communityIndex": 0
          }
        ],
        "consumption": {
          "collectionCount": 5113,
          "shareCount": 2588,
          "replyCount": 26,
          "realCollectionCount": 273
        },
        "resourceType": "video",
        "provider": {
          "name": "Vimeo",
          "alias": "vimeo",
          "icon": "http://img.kaiyanapp.com/c3ad630be461cbb081649c9e21d6cbe3.png"
        },
        "category": "动画",
        "author": {
          "id": 2170,
          "icon": "http://img.kaiyanapp.com/482c741c06644f5566c7218096dbaf26.jpeg",
          "name": "全球动画精选",
          "description": "我们精选全球最好看的动画短片，有趣的人永远不缺童心。",
          "link": "",
          "latestReleaseTime": 1634369080000,
          "videoNum": 1304,
          "follow": {
            "itemType": "author",
            "itemId": 2170,
            "followed": false
          },
          "shield": {
            "itemType": "author",
            "itemId": 2170,
            "shielded": false
          },
          "approvedNotReadyVideoCount": 0,
          "ifPgc": true,
          "recSort": 0,
          "expert": false
        },
        "cover": {
          "feed": "http://img.kaiyanapp.com/a078fc3c91bb046939de69e10932cc1f.jpeg?imageMogr2/quality/60/format/jpg",
          "detail": "http://img.kaiyanapp.com/a078fc3c91bb046939de69e10932cc1f.jpeg?imageMogr2/quality/60/format/jpg",
          "blurred": "http://img.kaiyanapp.com/6eef22acd07b3df580a14982d6d99fce.jpeg?imageMogr2/quality/60/format/jpg",
          "homepage": "http://img.kaiyanapp.com/a078fc3c91bb046939de69e10932cc1f.jpeg?imageView2/1/w/720/h/560/format/jpg/q/75|watermark/1/image/aHR0cDovL2ltZy5rYWl5YW5hcHAuY29tL2JsYWNrXzMwLnBuZw==/dissolve/100/gravity/Center/dx/0/dy/0|imageslim"
        },
        "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=173057&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
        "duration": 428,
        "webUrl": {
          "raw": "http://www.eyepetizer.net/detail.html?vid=173057",
          "forWeibo": "http://www.eyepetizer.net/detail.html?vid=173057&resourceType=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
        },
        "releaseTime": 1570410008000,
        "playInfo": [
          {
            "height": 720,
            "width": 1280,
            "urlList": [
              {
                "name": "aliyun",
                "url": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=173057&resourceType=video&editionType=high&source=aliyun&playUrlType=url_oss&udid=",
                "size": 31297838
              }
            ],
            "name": "高清",
            "type": "high",
            "url": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=173057&resourceType=video&editionType=high&source=aliyun&playUrlType=url_oss&udid="
          }
        ],
        "ad": false,
        "type": "NORMAL",
        "ifLimitVideo": false,
        "searchWeight": 0,
        "idx": 0,
        "date": 1570410008000,
        "descriptionEditor": "惠惠在搬家整理行李的时候，找到了爷爷心爱的黑熊纸镇，同时也是惠惠小时候最好的朋友：阿墨。虽然爷爷总是把纸镇收在玻璃柜裡，惠惠总是把阿墨当成玩伴带在身边，不论是洗澡、看书的时间、躲猫猫。阿墨好像参与惠惠所有的童年生活。From David Chao",
        "collected": false,
        "reallyCollected": false,
        "played": false
      },
      "id": 0,
      "adIndex": -1
    }
  },
  "id": 173057,
  "adIndex": -1
} 
*/

  String? type;
  ReelInfoItemListData? data;
  int? id;
  int? adIndex;

  ReelInfoItemList({
    this.type,
    this.data,
    this.id,
    this.adIndex,
  });
  ReelInfoItemList.fromJson(Map<String, dynamic> json) {
    type = json["type"]?.toString();
    data = (json["data"] != null)
        ? ReelInfoItemListData.fromJson(json["data"])
        : null;
    id = json["id"]?.toInt();
    adIndex = json["adIndex"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["type"] = type;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["id"] = id;
    data["adIndex"] = adIndex;
    return data;
  }
}

class ReelInfo {
/*
{
  "id": 651,
  "headerImage": "http://img.kaiyanapp.com/bb66e8eb830c8bd24e502fe17e94ad36.jpeg?imageMogr2/quality/60/format/jpg",
  "brief": " 吃货的重阳节也可以很酷！",
  "text": "重阳节除了记得问候家中长辈外，也要记得好好犒赏自己的胃！开眼为你准备了重阳糕、菊花酒、南瓜糍……赶快吃起来吧！PS：另外附赠温情重阳动画故事两则！",
  "shareLink": "http://www.eyepetizer.net/videos_article.html?nid=651&shareable=true",
  "itemList": [
    {
      "type": "autoPlayFollowCard",
      "data": {
        "dataType": "FollowCard",
        "header": {
          "id": 173057,
          "actionUrl": "eyepetizer://pgc/detail/2170/?title=%E5%85%A8%E7%90%83%E5%8A%A8%E7%94%BB%E7%B2%BE%E9%80%89&userType=PGC&tabIndex=1",
          "icon": "http://img.kaiyanapp.com/482c741c06644f5566c7218096dbaf26.jpeg",
          "iconType": "round",
          "time": 1570410008000,
          "showHateVideo": false,
          "followType": "author",
          "tagId": 0,
          "issuerName": "全球动画精选",
          "topShow": false
        },
        "content": {
          "type": "video",
          "data": {
            "dataType": "VideoBeanForClient",
            "id": 173057,
            "title": "重阳节特辑 |  我的爷爷，是只「黑熊」",
            "description": "惠惠在搬家整理行李的时候，找到了爷爷心爱的黑熊纸镇，同时也是惠惠小时候最好的朋友：阿墨。虽然爷爷总是把纸镇收在玻璃柜裡，惠惠总是把阿墨当成玩伴带在身边，不论是洗澡、看书的时间、躲猫猫。阿墨好像参与惠惠所有的童年生活。From David Chao",
            "library": "DAILY",
            "tags": [
              {
                "id": 14,
                "name": "动画梦工厂",
                "actionUrl": "eyepetizer://tag/14/?title=%E5%8A%A8%E7%94%BB%E6%A2%A6%E5%B7%A5%E5%8E%82",
                "desc": "有趣的人永远不缺童心",
                "bgPicture": "http://img.kaiyanapp.com/afb9e7d7f061d10ade5ebcb524dc8679.jpeg?imageMogr2/quality/60/format/jpg",
                "headerImage": "http://img.kaiyanapp.com/f9eae3e0321fa1e99a7b38641b5536a2.jpeg?imageMogr2/quality/60/format/jpg",
                "tagRecType": "IMPORTANT",
                "haveReward": false,
                "ifNewest": false,
                "communityIndex": 0
              }
            ],
            "consumption": {
              "collectionCount": 5113,
              "shareCount": 2588,
              "replyCount": 26,
              "realCollectionCount": 273
            },
            "resourceType": "video",
            "provider": {
              "name": "Vimeo",
              "alias": "vimeo",
              "icon": "http://img.kaiyanapp.com/c3ad630be461cbb081649c9e21d6cbe3.png"
            },
            "category": "动画",
            "author": {
              "id": 2170,
              "icon": "http://img.kaiyanapp.com/482c741c06644f5566c7218096dbaf26.jpeg",
              "name": "全球动画精选",
              "description": "我们精选全球最好看的动画短片，有趣的人永远不缺童心。",
              "link": "",
              "latestReleaseTime": 1634369080000,
              "videoNum": 1304,
              "follow": {
                "itemType": "author",
                "itemId": 2170,
                "followed": false
              },
              "shield": {
                "itemType": "author",
                "itemId": 2170,
                "shielded": false
              },
              "approvedNotReadyVideoCount": 0,
              "ifPgc": true,
              "recSort": 0,
              "expert": false
            },
            "cover": {
              "feed": "http://img.kaiyanapp.com/a078fc3c91bb046939de69e10932cc1f.jpeg?imageMogr2/quality/60/format/jpg",
              "detail": "http://img.kaiyanapp.com/a078fc3c91bb046939de69e10932cc1f.jpeg?imageMogr2/quality/60/format/jpg",
              "blurred": "http://img.kaiyanapp.com/6eef22acd07b3df580a14982d6d99fce.jpeg?imageMogr2/quality/60/format/jpg",
              "homepage": "http://img.kaiyanapp.com/a078fc3c91bb046939de69e10932cc1f.jpeg?imageView2/1/w/720/h/560/format/jpg/q/75|watermark/1/image/aHR0cDovL2ltZy5rYWl5YW5hcHAuY29tL2JsYWNrXzMwLnBuZw==/dissolve/100/gravity/Center/dx/0/dy/0|imageslim"
            },
            "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=173057&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
            "duration": 428,
            "webUrl": {
              "raw": "http://www.eyepetizer.net/detail.html?vid=173057",
              "forWeibo": "http://www.eyepetizer.net/detail.html?vid=173057&resourceType=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
            },
            "releaseTime": 1570410008000,
            "playInfo": [
              {
                "height": 720,
                "width": 1280,
                "urlList": [
                  {
                    "name": "aliyun",
                    "url": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=173057&resourceType=video&editionType=high&source=aliyun&playUrlType=url_oss&udid=",
                    "size": 31297838
                  }
                ],
                "name": "高清",
                "type": "high",
                "url": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=173057&resourceType=video&editionType=high&source=aliyun&playUrlType=url_oss&udid="
              }
            ],
            "ad": false,
            "type": "NORMAL",
            "ifLimitVideo": false,
            "searchWeight": 0,
            "idx": 0,
            "date": 1570410008000,
            "descriptionEditor": "惠惠在搬家整理行李的时候，找到了爷爷心爱的黑熊纸镇，同时也是惠惠小时候最好的朋友：阿墨。虽然爷爷总是把纸镇收在玻璃柜裡，惠惠总是把阿墨当成玩伴带在身边，不论是洗澡、看书的时间、躲猫猫。阿墨好像参与惠惠所有的童年生活。From David Chao",
            "collected": false,
            "reallyCollected": false,
            "played": false
          },
          "id": 0,
          "adIndex": -1
        }
      },
      "id": 173057,
      "adIndex": -1
    }
  ],
  "count": 6
} 
*/

  int? id;
  String? headerImage;
  String? brief;
  String? text;
  String? shareLink;
  List<ReelInfoItemList?>? itemList;
  int? count;

  ReelInfo({
    this.id,
    this.headerImage,
    this.brief,
    this.text,
    this.shareLink,
    this.itemList,
    this.count,
  });
  ReelInfo.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    headerImage = json["headerImage"]?.toString();
    brief = json["brief"]?.toString();
    text = json["text"]?.toString();
    shareLink = json["shareLink"]?.toString();
    if (json["itemList"] != null) {
      final v = json["itemList"];
      final arr0 = <ReelInfoItemList>[];
      v.forEach((v) {
        arr0.add(ReelInfoItemList.fromJson(v));
      });
      itemList = arr0;
    }
    count = json["count"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["headerImage"] = headerImage;
    data["brief"] = brief;
    data["text"] = text;
    data["shareLink"] = shareLink;
    if (itemList != null) {
      final v = itemList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["itemList"] = arr0;
    }
    data["count"] = count;
    return data;
  }
}
