///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TypesData {
/*
{
  "id": 14,
  "name": "广告",
  "description": "为广告人的精彩创意点赞",
  "bgPicture": "http://img.kaiyanapp.com/57472e13fd2b6c9655c8a600597daf4d.png?imageMogr2/quality/60/format/jpg",
  "bgColor": "",
  "headerImage": "http://img.kaiyanapp.com/fc228d16638214b9803f46aabb4f75e0.png",
  "defaultAuthorId": 2162,
  "tagId": 16
} 
*/

  int? id;
  String? name;
  String? description;
  String? bgPicture;
  String? bgColor;
  String? headerImage;
  int? defaultAuthorId;
  int? tagId;

  TypesData({
    this.id,
    this.name,
    this.description,
    this.bgPicture,
    this.bgColor,
    this.headerImage,
    this.defaultAuthorId,
    this.tagId,
  });
  TypesData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    name = json["name"]?.toString();
    description = json["description"]?.toString();
    bgPicture = json["bgPicture"]?.toString();
    bgColor = json["bgColor"]?.toString();
    headerImage = json["headerImage"]?.toString();
    defaultAuthorId = json["defaultAuthorId"]?.toInt();
    tagId = json["tagId"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["description"] = description;
    data["bgPicture"] = bgPicture;
    data["bgColor"] = bgColor;
    data["headerImage"] = headerImage;
    data["defaultAuthorId"] = defaultAuthorId;
    data["tagId"] = tagId;
    return data;
  }
}

class Types {
/*
{
  "data": [
    {
      "id": 14,
      "name": "广告",
      "description": "为广告人的精彩创意点赞",
      "bgPicture": "http://img.kaiyanapp.com/57472e13fd2b6c9655c8a600597daf4d.png?imageMogr2/quality/60/format/jpg",
      "bgColor": "",
      "headerImage": "http://img.kaiyanapp.com/fc228d16638214b9803f46aabb4f75e0.png",
      "defaultAuthorId": 2162,
      "tagId": 16
    }
  ]
} 
*/

  List<TypesData?>? data;

  Types({
    this.data,
  });
  Types.fromJson(List<dynamic> data) {
    final arr0 = <TypesData>[];
    data.forEach((v) {
      arr0.add(TypesData.fromJson(v));
    });
    this.data = arr0;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["data"] = arr0;
    }
    return data;
  }
}
