///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class VideoRelatedItemListDataPlayInfoUrlList {
/*
{
  "name": "aliyun",
  "url": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=282082&resourceType=video&editionType=normal&source=aliyun&playUrlType=url_oss&udid=",
  "size": 35951690
} 
*/

  String? name;
  String? url;
  int? size;

  VideoRelatedItemListDataPlayInfoUrlList({
    this.name,
    this.url,
    this.size,
  });
  VideoRelatedItemListDataPlayInfoUrlList.fromJson(Map<String, dynamic> json) {
    name = json["name"]?.toString();
    url = json["url"]?.toString();
    size = json["size"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["name"] = name;
    data["url"] = url;
    data["size"] = size;
    return data;
  }
}

class VideoRelatedItemListDataPlayInfo {
/*
{
  "height": 480,
  "width": 854,
  "urlList": [
    {
      "name": "aliyun",
      "url": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=282082&resourceType=video&editionType=normal&source=aliyun&playUrlType=url_oss&udid=",
      "size": 35951690
    }
  ],
  "name": "标清",
  "type": "normal",
  "url": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=282082&resourceType=video&editionType=normal&source=aliyun&playUrlType=url_oss&udid="
} 
*/

  int? height;
  int? width;
  List<VideoRelatedItemListDataPlayInfoUrlList?>? urlList;
  String? name;
  String? type;
  String? url;

  VideoRelatedItemListDataPlayInfo({
    this.height,
    this.width,
    this.urlList,
    this.name,
    this.type,
    this.url,
  });
  VideoRelatedItemListDataPlayInfo.fromJson(Map<String, dynamic> json) {
    height = json["height"]?.toInt();
    width = json["width"]?.toInt();
    if (json["urlList"] != null) {
      final v = json["urlList"];
      final arr0 = <VideoRelatedItemListDataPlayInfoUrlList>[];
      v.forEach((v) {
        arr0.add(VideoRelatedItemListDataPlayInfoUrlList.fromJson(v));
      });
      urlList = arr0;
    }
    name = json["name"]?.toString();
    type = json["type"]?.toString();
    url = json["url"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["height"] = height;
    data["width"] = width;
    if (urlList != null) {
      final v = urlList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["urlList"] = arr0;
    }
    data["name"] = name;
    data["type"] = type;
    data["url"] = url;
    return data;
  }
}

class VideoRelatedItemListDataWebUrl {
/*
{
  "raw": "http://www.eyepetizer.net/detail.html?vid=282082",
  "forWeibo": "https://m.eyepetizer.net/u1/video-detail?video_id=282082&resource_type=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
} 
*/

  String? raw;
  String? forWeibo;

  VideoRelatedItemListDataWebUrl({
    this.raw,
    this.forWeibo,
  });
  VideoRelatedItemListDataWebUrl.fromJson(Map<String, dynamic> json) {
    raw = json["raw"]?.toString();
    forWeibo = json["forWeibo"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["raw"] = raw;
    data["forWeibo"] = forWeibo;
    return data;
  }
}

class VideoRelatedItemListDataCover {
/*
{
  "feed": "http://img.kaiyanapp.com/58b4235de59edecefc73246d1b6cd5e0.jpeg?imageMogr2/quality/60/format/jpg",
  "detail": "http://img.kaiyanapp.com/58b4235de59edecefc73246d1b6cd5e0.jpeg?imageMogr2/quality/60/format/jpg",
  "blurred": "http://img.kaiyanapp.com/32c2049f6458e77de6a3a992e320780a.jpeg?imageMogr2/quality/60/format/jpg"
} 
*/

  String? feed;
  String? detail;
  String? blurred;

  VideoRelatedItemListDataCover({
    this.feed,
    this.detail,
    this.blurred,
  });
  VideoRelatedItemListDataCover.fromJson(Map<String, dynamic> json) {
    feed = json["feed"]?.toString();
    detail = json["detail"]?.toString();
    blurred = json["blurred"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["feed"] = feed;
    data["detail"] = detail;
    data["blurred"] = blurred;
    return data;
  }
}

class VideoRelatedItemListDataAuthorShield {
/*
{
  "itemType": "author",
  "itemId": 1551,
  "shielded": false
} 
*/

  String? itemType;
  int? itemId;
  bool? shielded;

  VideoRelatedItemListDataAuthorShield({
    this.itemType,
    this.itemId,
    this.shielded,
  });
  VideoRelatedItemListDataAuthorShield.fromJson(Map<String, dynamic> json) {
    itemType = json["itemType"]?.toString();
    itemId = json["itemId"]?.toInt();
    shielded = json["shielded"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["itemType"] = itemType;
    data["itemId"] = itemId;
    data["shielded"] = shielded;
    return data;
  }
}

class VideoRelatedItemListDataAuthorFollow {
/*
{
  "itemType": "author",
  "itemId": 1551,
  "followed": false
} 
*/

  String? itemType;
  int? itemId;
  bool? followed;

  VideoRelatedItemListDataAuthorFollow({
    this.itemType,
    this.itemId,
    this.followed,
  });
  VideoRelatedItemListDataAuthorFollow.fromJson(Map<String, dynamic> json) {
    itemType = json["itemType"]?.toString();
    itemId = json["itemId"]?.toInt();
    followed = json["followed"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["itemType"] = itemType;
    data["itemId"] = itemId;
    data["followed"] = followed;
    return data;
  }
}

class VideoRelatedItemListDataAuthor {
/*
{
  "id": 1551,
  "icon": "http://img.kaiyanapp.com/cf21caef638a5f377a360404c358eb13.jpeg?imageMogr2/quality/60/format/jpg",
  "name": "乐高世界",
  "description": "用不起眼的小方块，拼出你想象不到的世界。",
  "link": "",
  "latestReleaseTime": 1634524283000,
  "videoNum": 222,
  "follow": {
    "itemType": "author",
    "itemId": 1551,
    "followed": false
  },
  "shield": {
    "itemType": "author",
    "itemId": 1551,
    "shielded": false
  },
  "approvedNotReadyVideoCount": 0,
  "ifPgc": true,
  "recSort": 0,
  "expert": false
} 
*/

  int? id;
  String? icon;
  String? name;
  String? description;
  String? link;
  int? latestReleaseTime;
  int? videoNum;
  VideoRelatedItemListDataAuthorFollow? follow;
  VideoRelatedItemListDataAuthorShield? shield;
  int? approvedNotReadyVideoCount;
  bool? ifPgc;
  int? recSort;
  bool? expert;

  VideoRelatedItemListDataAuthor({
    this.id,
    this.icon,
    this.name,
    this.description,
    this.link,
    this.latestReleaseTime,
    this.videoNum,
    this.follow,
    this.shield,
    this.approvedNotReadyVideoCount,
    this.ifPgc,
    this.recSort,
    this.expert,
  });
  VideoRelatedItemListDataAuthor.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    icon = json["icon"]?.toString();
    name = json["name"]?.toString();
    description = json["description"]?.toString();
    link = json["link"]?.toString();
    latestReleaseTime = json["latestReleaseTime"]?.toInt();
    videoNum = json["videoNum"]?.toInt();
    follow = (json["follow"] != null)
        ? VideoRelatedItemListDataAuthorFollow.fromJson(json["follow"])
        : null;
    shield = (json["shield"] != null)
        ? VideoRelatedItemListDataAuthorShield.fromJson(json["shield"])
        : null;
    approvedNotReadyVideoCount = json["approvedNotReadyVideoCount"]?.toInt();
    ifPgc = json["ifPgc"];
    recSort = json["recSort"]?.toInt();
    expert = json["expert"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["icon"] = icon;
    data["name"] = name;
    data["description"] = description;
    data["link"] = link;
    data["latestReleaseTime"] = latestReleaseTime;
    data["videoNum"] = videoNum;
    if (follow != null) {
      data["follow"] = follow!.toJson();
    }
    if (shield != null) {
      data["shield"] = shield!.toJson();
    }
    data["approvedNotReadyVideoCount"] = approvedNotReadyVideoCount;
    data["ifPgc"] = ifPgc;
    data["recSort"] = recSort;
    data["expert"] = expert;
    return data;
  }
}

class VideoRelatedItemListDataProvider {
/*
{
  "name": "定制来源",
  "alias": "CustomSrc",
  "icon": ""
} 
*/

  String? name;
  String? alias;
  String? icon;

  VideoRelatedItemListDataProvider({
    this.name,
    this.alias,
    this.icon,
  });
  VideoRelatedItemListDataProvider.fromJson(Map<String, dynamic> json) {
    name = json["name"]?.toString();
    alias = json["alias"]?.toString();
    icon = json["icon"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["name"] = name;
    data["alias"] = alias;
    data["icon"] = icon;
    return data;
  }
}

class VideoRelatedItemListData {
/*
{
  "dataType": "VideoBeanForClient",
  "id": 282082,
  "title": "乐高复仇者系列：战争机器破坏者",
  "description": "这是乐高复仇者系列中的一款游戏：战争机器破坏者，你喜欢复仇者联盟吗？你有见过战争机器破坏者的样子吗？来乐高吧，从这个视频中你将知道！",
  "library": "DEFAULT",
  "resourceType": "video",
  "provider": {
    "name": "定制来源",
    "alias": "CustomSrc",
    "icon": ""
  },
  "category": "游戏",
  "author": {
    "id": 1551,
    "icon": "http://img.kaiyanapp.com/cf21caef638a5f377a360404c358eb13.jpeg?imageMogr2/quality/60/format/jpg",
    "name": "乐高世界",
    "description": "用不起眼的小方块，拼出你想象不到的世界。",
    "link": "",
    "latestReleaseTime": 1634524283000,
    "videoNum": 222,
    "follow": {
      "itemType": "author",
      "itemId": 1551,
      "followed": false
    },
    "shield": {
      "itemType": "author",
      "itemId": 1551,
      "shielded": false
    },
    "approvedNotReadyVideoCount": 0,
    "ifPgc": true,
    "recSort": 0,
    "expert": false
  },
  "cover": {
    "feed": "http://img.kaiyanapp.com/58b4235de59edecefc73246d1b6cd5e0.jpeg?imageMogr2/quality/60/format/jpg",
    "detail": "http://img.kaiyanapp.com/58b4235de59edecefc73246d1b6cd5e0.jpeg?imageMogr2/quality/60/format/jpg",
    "blurred": "http://img.kaiyanapp.com/32c2049f6458e77de6a3a992e320780a.jpeg?imageMogr2/quality/60/format/jpg"
  },
  "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=282082&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
  "duration": 433,
  "webUrl": {
    "raw": "http://www.eyepetizer.net/detail.html?vid=282082",
    "forWeibo": "https://m.eyepetizer.net/u1/video-detail?video_id=282082&resource_type=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
  },
  "releaseTime": 1634385009000,
  "playInfo": [
    {
      "height": 480,
      "width": 854,
      "urlList": [
        {
          "name": "aliyun",
          "url": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=282082&resourceType=video&editionType=normal&source=aliyun&playUrlType=url_oss&udid=",
          "size": 35951690
        }
      ],
      "name": "标清",
      "type": "normal",
      "url": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=282082&resourceType=video&editionType=normal&source=aliyun&playUrlType=url_oss&udid="
    }
  ],
  "type": "NORMAL",
  "titlePgc": "乐高复仇者系列：战争机器破坏者",
  "descriptionPgc": "这是乐高复仇者系列中的一款游戏：战争机器破坏者，你喜欢复仇者联盟吗？你有见过战争机器破坏者的样子吗？来乐高吧，从这个视频中你将知道！",
  "ifLimitVideo": false,
  "searchWeight": 0,
  "idx": 0,
  "date": 1634385009000,
  "descriptionEditor": "",
  "collected": false,
  "reallyCollected": false,
  "played": false
} 
*/

  String? dataType;
  int? id;
  String? title;
  String? description;
  String? theLibrary;
  String? resourceType;
  VideoRelatedItemListDataProvider? provider;
  String? category;
  VideoRelatedItemListDataAuthor? author;
  VideoRelatedItemListDataCover? cover;
  String? playUrl;
  int? duration;
  VideoRelatedItemListDataWebUrl? webUrl;
  int? releaseTime;
  List<VideoRelatedItemListDataPlayInfo?>? playInfo;
  String? type;
  String? titlePgc;
  String? descriptionPgc;
  bool? ifLimitVideo;
  int? searchWeight;
  int? idx;
  int? date;
  String? descriptionEditor;
  bool? collected;
  bool? reallyCollected;
  bool? played;

  VideoRelatedItemListData({
    this.dataType,
    this.id,
    this.title,
    this.description,
    this.theLibrary,
    this.resourceType,
    this.provider,
    this.category,
    this.author,
    this.cover,
    this.playUrl,
    this.duration,
    this.webUrl,
    this.releaseTime,
    this.playInfo,
    this.type,
    this.titlePgc,
    this.descriptionPgc,
    this.ifLimitVideo,
    this.searchWeight,
    this.idx,
    this.date,
    this.descriptionEditor,
    this.collected,
    this.reallyCollected,
    this.played,
  });
  VideoRelatedItemListData.fromJson(Map<String, dynamic> json) {
    dataType = json["dataType"]?.toString();
    id = json["id"]?.toInt();
    title = json["title"]?.toString();
    description = json["description"]?.toString();
    theLibrary = json["library"]?.toString();
    resourceType = json["resourceType"]?.toString();
    provider = (json["provider"] != null)
        ? VideoRelatedItemListDataProvider.fromJson(json["provider"])
        : null;
    category = json["category"]?.toString();
    author = (json["author"] != null)
        ? VideoRelatedItemListDataAuthor.fromJson(json["author"])
        : null;
    cover = (json["cover"] != null)
        ? VideoRelatedItemListDataCover.fromJson(json["cover"])
        : null;
    playUrl = json["playUrl"]?.toString();
    duration = json["duration"]?.toInt();
    webUrl = (json["webUrl"] != null)
        ? VideoRelatedItemListDataWebUrl.fromJson(json["webUrl"])
        : null;
    releaseTime = json["releaseTime"]?.toInt();
    if (json["playInfo"] != null) {
      final v = json["playInfo"];
      final arr0 = <VideoRelatedItemListDataPlayInfo>[];
      v.forEach((v) {
        arr0.add(VideoRelatedItemListDataPlayInfo.fromJson(v));
      });
      playInfo = arr0;
    }
    type = json["type"]?.toString();
    titlePgc = json["titlePgc"]?.toString();
    descriptionPgc = json["descriptionPgc"]?.toString();
    ifLimitVideo = json["ifLimitVideo"];
    searchWeight = json["searchWeight"]?.toInt();
    idx = json["idx"]?.toInt();
    date = json["date"]?.toInt();
    descriptionEditor = json["descriptionEditor"]?.toString();
    collected = json["collected"];
    reallyCollected = json["reallyCollected"];
    played = json["played"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["dataType"] = dataType;
    data["id"] = id;
    data["title"] = title;
    data["description"] = description;
    data["library"] = theLibrary;
    data["resourceType"] = resourceType;
    if (provider != null) {
      data["provider"] = provider!.toJson();
    }
    data["category"] = category;
    if (author != null) {
      data["author"] = author!.toJson();
    }
    if (cover != null) {
      data["cover"] = cover!.toJson();
    }
    data["playUrl"] = playUrl;
    data["duration"] = duration;
    if (webUrl != null) {
      data["webUrl"] = webUrl!.toJson();
    }
    data["releaseTime"] = releaseTime;
    if (playInfo != null) {
      final v = playInfo;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["playInfo"] = arr0;
    }
    data["type"] = type;
    data["titlePgc"] = titlePgc;
    data["descriptionPgc"] = descriptionPgc;
    data["ifLimitVideo"] = ifLimitVideo;
    data["searchWeight"] = searchWeight;
    data["idx"] = idx;
    data["date"] = date;
    data["descriptionEditor"] = descriptionEditor;
    data["collected"] = collected;
    data["reallyCollected"] = reallyCollected;
    data["played"] = played;
    return data;
  }
}

class VideoRelatedItemList {
/*
{
  "type": "videoSmallCard",
  "data": {
    "dataType": "VideoBeanForClient",
    "id": 282082,
    "title": "乐高复仇者系列：战争机器破坏者",
    "description": "这是乐高复仇者系列中的一款游戏：战争机器破坏者，你喜欢复仇者联盟吗？你有见过战争机器破坏者的样子吗？来乐高吧，从这个视频中你将知道！",
    "library": "DEFAULT",
    "resourceType": "video",
    "provider": {
      "name": "定制来源",
      "alias": "CustomSrc",
      "icon": ""
    },
    "category": "游戏",
    "author": {
      "id": 1551,
      "icon": "http://img.kaiyanapp.com/cf21caef638a5f377a360404c358eb13.jpeg?imageMogr2/quality/60/format/jpg",
      "name": "乐高世界",
      "description": "用不起眼的小方块，拼出你想象不到的世界。",
      "link": "",
      "latestReleaseTime": 1634524283000,
      "videoNum": 222,
      "follow": {
        "itemType": "author",
        "itemId": 1551,
        "followed": false
      },
      "shield": {
        "itemType": "author",
        "itemId": 1551,
        "shielded": false
      },
      "approvedNotReadyVideoCount": 0,
      "ifPgc": true,
      "recSort": 0,
      "expert": false
    },
    "cover": {
      "feed": "http://img.kaiyanapp.com/58b4235de59edecefc73246d1b6cd5e0.jpeg?imageMogr2/quality/60/format/jpg",
      "detail": "http://img.kaiyanapp.com/58b4235de59edecefc73246d1b6cd5e0.jpeg?imageMogr2/quality/60/format/jpg",
      "blurred": "http://img.kaiyanapp.com/32c2049f6458e77de6a3a992e320780a.jpeg?imageMogr2/quality/60/format/jpg"
    },
    "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=282082&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
    "duration": 433,
    "webUrl": {
      "raw": "http://www.eyepetizer.net/detail.html?vid=282082",
      "forWeibo": "https://m.eyepetizer.net/u1/video-detail?video_id=282082&resource_type=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
    },
    "releaseTime": 1634385009000,
    "playInfo": [
      {
        "height": 480,
        "width": 854,
        "urlList": [
          {
            "name": "aliyun",
            "url": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=282082&resourceType=video&editionType=normal&source=aliyun&playUrlType=url_oss&udid=",
            "size": 35951690
          }
        ],
        "name": "标清",
        "type": "normal",
        "url": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=282082&resourceType=video&editionType=normal&source=aliyun&playUrlType=url_oss&udid="
      }
    ],
    "type": "NORMAL",
    "titlePgc": "乐高复仇者系列：战争机器破坏者",
    "descriptionPgc": "这是乐高复仇者系列中的一款游戏：战争机器破坏者，你喜欢复仇者联盟吗？你有见过战争机器破坏者的样子吗？来乐高吧，从这个视频中你将知道！",
    "ifLimitVideo": false,
    "searchWeight": 0,
    "idx": 0,
    "date": 1634385009000,
    "descriptionEditor": "",
    "collected": false,
    "reallyCollected": false,
    "played": false
  },
  "id": 0,
  "adIndex": -1
} 
*/

  String? type;
  VideoRelatedItemListData? data;
  int? id;
  int? adIndex;

  VideoRelatedItemList({
    this.type,
    this.data,
    this.id,
    this.adIndex,
  });
  VideoRelatedItemList.fromJson(Map<String, dynamic> json) {
    type = json["type"]?.toString();
    data = (json["data"] != null)
        ? VideoRelatedItemListData.fromJson(json["data"])
        : null;
    id = json["id"]?.toInt();
    adIndex = json["adIndex"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["type"] = type;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["id"] = id;
    data["adIndex"] = adIndex;
    return data;
  }
}

class VideoRelated {
/*
{
  "itemList": [
    {
      "type": "videoSmallCard",
      "data": {
        "dataType": "VideoBeanForClient",
        "id": 282082,
        "title": "乐高复仇者系列：战争机器破坏者",
        "description": "这是乐高复仇者系列中的一款游戏：战争机器破坏者，你喜欢复仇者联盟吗？你有见过战争机器破坏者的样子吗？来乐高吧，从这个视频中你将知道！",
        "library": "DEFAULT",
        "resourceType": "video",
        "provider": {
          "name": "定制来源",
          "alias": "CustomSrc",
          "icon": ""
        },
        "category": "游戏",
        "author": {
          "id": 1551,
          "icon": "http://img.kaiyanapp.com/cf21caef638a5f377a360404c358eb13.jpeg?imageMogr2/quality/60/format/jpg",
          "name": "乐高世界",
          "description": "用不起眼的小方块，拼出你想象不到的世界。",
          "link": "",
          "latestReleaseTime": 1634524283000,
          "videoNum": 222,
          "follow": {
            "itemType": "author",
            "itemId": 1551,
            "followed": false
          },
          "shield": {
            "itemType": "author",
            "itemId": 1551,
            "shielded": false
          },
          "approvedNotReadyVideoCount": 0,
          "ifPgc": true,
          "recSort": 0,
          "expert": false
        },
        "cover": {
          "feed": "http://img.kaiyanapp.com/58b4235de59edecefc73246d1b6cd5e0.jpeg?imageMogr2/quality/60/format/jpg",
          "detail": "http://img.kaiyanapp.com/58b4235de59edecefc73246d1b6cd5e0.jpeg?imageMogr2/quality/60/format/jpg",
          "blurred": "http://img.kaiyanapp.com/32c2049f6458e77de6a3a992e320780a.jpeg?imageMogr2/quality/60/format/jpg"
        },
        "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=282082&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
        "duration": 433,
        "webUrl": {
          "raw": "http://www.eyepetizer.net/detail.html?vid=282082",
          "forWeibo": "https://m.eyepetizer.net/u1/video-detail?video_id=282082&resource_type=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
        },
        "releaseTime": 1634385009000,
        "playInfo": [
          {
            "height": 480,
            "width": 854,
            "urlList": [
              {
                "name": "aliyun",
                "url": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=282082&resourceType=video&editionType=normal&source=aliyun&playUrlType=url_oss&udid=",
                "size": 35951690
              }
            ],
            "name": "标清",
            "type": "normal",
            "url": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=282082&resourceType=video&editionType=normal&source=aliyun&playUrlType=url_oss&udid="
          }
        ],
        "type": "NORMAL",
        "titlePgc": "乐高复仇者系列：战争机器破坏者",
        "descriptionPgc": "这是乐高复仇者系列中的一款游戏：战争机器破坏者，你喜欢复仇者联盟吗？你有见过战争机器破坏者的样子吗？来乐高吧，从这个视频中你将知道！",
        "ifLimitVideo": false,
        "searchWeight": 0,
        "idx": 0,
        "date": 1634385009000,
        "descriptionEditor": "",
        "collected": false,
        "reallyCollected": false,
        "played": false
      },
      "id": 0,
      "adIndex": -1
    }
  ],
  "count": 48,
  "total": 0,
  "adExist": false
} 
*/

  List<VideoRelatedItemList?>? itemList;
  int? count;
  int? total;
  bool? adExist;

  VideoRelated({
    this.itemList,
    this.count,
    this.total,
    this.adExist,
  });
  VideoRelated.fromJson(Map<String, dynamic> json) {
    if (json["itemList"] != null) {
      final v = json["itemList"];
      final arr0 = <VideoRelatedItemList>[];
      v.forEach((v) {
        if (v["type"] == "videoSmallCard") {
          arr0.add(VideoRelatedItemList.fromJson(v));
        }
      });
      itemList = arr0;
    }
    count = json["count"]?.toInt();
    total = json["total"]?.toInt();
    adExist = json["adExist"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (itemList != null) {
      final v = itemList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["itemList"] = arr0;
    }
    data["count"] = count;
    data["total"] = total;
    data["adExist"] = adExist;
    return data;
  }
}
